// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: catalog-system/catalog.proto

package catalogpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CatalogService_CreateContent_FullMethodName         = "/catalog.CatalogService/CreateContent"
	CatalogService_GetContent_FullMethodName            = "/catalog.CatalogService/GetContent"
	CatalogService_GetContentByIDs_FullMethodName       = "/catalog.CatalogService/GetContentByIDs"
	CatalogService_UpdateContent_FullMethodName         = "/catalog.CatalogService/UpdateContent"
	CatalogService_FindContentByExternal_FullMethodName = "/catalog.CatalogService/FindContentByExternal"
	CatalogService_GetMovieDetails_FullMethodName       = "/catalog.CatalogService/GetMovieDetails"
	CatalogService_GetAnimeDetails_FullMethodName       = "/catalog.CatalogService/GetAnimeDetails"
	CatalogService_GetGameDetails_FullMethodName        = "/catalog.CatalogService/GetGameDetails"
	CatalogService_GetSeriesDetails_FullMethodName      = "/catalog.CatalogService/GetSeriesDetails"
	CatalogService_GetBookDetails_FullMethodName        = "/catalog.CatalogService/GetBookDetails"
	CatalogService_GetAllMovieDetails_FullMethodName    = "/catalog.CatalogService/GetAllMovieDetails"
	CatalogService_GetAllAnimeDetails_FullMethodName    = "/catalog.CatalogService/GetAllAnimeDetails"
	CatalogService_GetAllGameDetails_FullMethodName     = "/catalog.CatalogService/GetAllGameDetails"
	CatalogService_GetAllSeriesDetails_FullMethodName   = "/catalog.CatalogService/GetAllSeriesDetails"
	CatalogService_GetAllBookDetails_FullMethodName     = "/catalog.CatalogService/GetAllBookDetails"
)

// CatalogServiceClient is the client API for CatalogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CatalogServiceClient interface {
	CreateContent(ctx context.Context, in *CreateContentRequest, opts ...grpc.CallOption) (*CreateContentResponse, error)
	GetContent(ctx context.Context, in *GetContentRequest, opts ...grpc.CallOption) (*GetContentResponse, error)
	GetContentByIDs(ctx context.Context, in *GetContentByIDsRequest, opts ...grpc.CallOption) (*GetContentByIDsResponse, error)
	UpdateContent(ctx context.Context, in *UpdateContentRequest, opts ...grpc.CallOption) (*UpdateContentResponse, error)
	FindContentByExternal(ctx context.Context, in *FindContentByExternalRequest, opts ...grpc.CallOption) (*FindContentByExternalResponse, error)
	GetMovieDetails(ctx context.Context, in *GetMovieDetailsRequest, opts ...grpc.CallOption) (*GetMovieDetailsResponse, error)
	GetAnimeDetails(ctx context.Context, in *GetAnimeDetailsRequest, opts ...grpc.CallOption) (*GetAnimeDetailsResponse, error)
	GetGameDetails(ctx context.Context, in *GetGameDetailsRequest, opts ...grpc.CallOption) (*GetGameDetailsResponse, error)
	GetSeriesDetails(ctx context.Context, in *GetSeriesDetailsRequest, opts ...grpc.CallOption) (*GetSeriesDetailsResponse, error)
	GetBookDetails(ctx context.Context, in *GetBookDetailsRequest, opts ...grpc.CallOption) (*GetBookDetailsResponse, error)
	GetAllMovieDetails(ctx context.Context, in *GetAllMovieDetailsRequest, opts ...grpc.CallOption) (*GetAllMovieDetailsResponse, error)
	GetAllAnimeDetails(ctx context.Context, in *GetAllAnimeDetailsRequest, opts ...grpc.CallOption) (*GetAllAnimeDetailsResponse, error)
	GetAllGameDetails(ctx context.Context, in *GetAllGameDetailsRequest, opts ...grpc.CallOption) (*GetAllGameDetailsResponse, error)
	GetAllSeriesDetails(ctx context.Context, in *GetAllSeriesDetailsRequest, opts ...grpc.CallOption) (*GetAllSeriesDetailsResponse, error)
	GetAllBookDetails(ctx context.Context, in *GetAllBookDetailsRequest, opts ...grpc.CallOption) (*GetAllBookDetailsResponse, error)
}

type catalogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCatalogServiceClient(cc grpc.ClientConnInterface) CatalogServiceClient {
	return &catalogServiceClient{cc}
}

func (c *catalogServiceClient) CreateContent(ctx context.Context, in *CreateContentRequest, opts ...grpc.CallOption) (*CreateContentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateContentResponse)
	err := c.cc.Invoke(ctx, CatalogService_CreateContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetContent(ctx context.Context, in *GetContentRequest, opts ...grpc.CallOption) (*GetContentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetContentResponse)
	err := c.cc.Invoke(ctx, CatalogService_GetContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetContentByIDs(ctx context.Context, in *GetContentByIDsRequest, opts ...grpc.CallOption) (*GetContentByIDsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetContentByIDsResponse)
	err := c.cc.Invoke(ctx, CatalogService_GetContentByIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) UpdateContent(ctx context.Context, in *UpdateContentRequest, opts ...grpc.CallOption) (*UpdateContentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateContentResponse)
	err := c.cc.Invoke(ctx, CatalogService_UpdateContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) FindContentByExternal(ctx context.Context, in *FindContentByExternalRequest, opts ...grpc.CallOption) (*FindContentByExternalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindContentByExternalResponse)
	err := c.cc.Invoke(ctx, CatalogService_FindContentByExternal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetMovieDetails(ctx context.Context, in *GetMovieDetailsRequest, opts ...grpc.CallOption) (*GetMovieDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMovieDetailsResponse)
	err := c.cc.Invoke(ctx, CatalogService_GetMovieDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetAnimeDetails(ctx context.Context, in *GetAnimeDetailsRequest, opts ...grpc.CallOption) (*GetAnimeDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAnimeDetailsResponse)
	err := c.cc.Invoke(ctx, CatalogService_GetAnimeDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetGameDetails(ctx context.Context, in *GetGameDetailsRequest, opts ...grpc.CallOption) (*GetGameDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGameDetailsResponse)
	err := c.cc.Invoke(ctx, CatalogService_GetGameDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetSeriesDetails(ctx context.Context, in *GetSeriesDetailsRequest, opts ...grpc.CallOption) (*GetSeriesDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSeriesDetailsResponse)
	err := c.cc.Invoke(ctx, CatalogService_GetSeriesDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetBookDetails(ctx context.Context, in *GetBookDetailsRequest, opts ...grpc.CallOption) (*GetBookDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBookDetailsResponse)
	err := c.cc.Invoke(ctx, CatalogService_GetBookDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetAllMovieDetails(ctx context.Context, in *GetAllMovieDetailsRequest, opts ...grpc.CallOption) (*GetAllMovieDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllMovieDetailsResponse)
	err := c.cc.Invoke(ctx, CatalogService_GetAllMovieDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetAllAnimeDetails(ctx context.Context, in *GetAllAnimeDetailsRequest, opts ...grpc.CallOption) (*GetAllAnimeDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllAnimeDetailsResponse)
	err := c.cc.Invoke(ctx, CatalogService_GetAllAnimeDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetAllGameDetails(ctx context.Context, in *GetAllGameDetailsRequest, opts ...grpc.CallOption) (*GetAllGameDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllGameDetailsResponse)
	err := c.cc.Invoke(ctx, CatalogService_GetAllGameDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetAllSeriesDetails(ctx context.Context, in *GetAllSeriesDetailsRequest, opts ...grpc.CallOption) (*GetAllSeriesDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllSeriesDetailsResponse)
	err := c.cc.Invoke(ctx, CatalogService_GetAllSeriesDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetAllBookDetails(ctx context.Context, in *GetAllBookDetailsRequest, opts ...grpc.CallOption) (*GetAllBookDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllBookDetailsResponse)
	err := c.cc.Invoke(ctx, CatalogService_GetAllBookDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatalogServiceServer is the server API for CatalogService service.
// All implementations must embed UnimplementedCatalogServiceServer
// for forward compatibility.
type CatalogServiceServer interface {
	CreateContent(context.Context, *CreateContentRequest) (*CreateContentResponse, error)
	GetContent(context.Context, *GetContentRequest) (*GetContentResponse, error)
	GetContentByIDs(context.Context, *GetContentByIDsRequest) (*GetContentByIDsResponse, error)
	UpdateContent(context.Context, *UpdateContentRequest) (*UpdateContentResponse, error)
	FindContentByExternal(context.Context, *FindContentByExternalRequest) (*FindContentByExternalResponse, error)
	GetMovieDetails(context.Context, *GetMovieDetailsRequest) (*GetMovieDetailsResponse, error)
	GetAnimeDetails(context.Context, *GetAnimeDetailsRequest) (*GetAnimeDetailsResponse, error)
	GetGameDetails(context.Context, *GetGameDetailsRequest) (*GetGameDetailsResponse, error)
	GetSeriesDetails(context.Context, *GetSeriesDetailsRequest) (*GetSeriesDetailsResponse, error)
	GetBookDetails(context.Context, *GetBookDetailsRequest) (*GetBookDetailsResponse, error)
	GetAllMovieDetails(context.Context, *GetAllMovieDetailsRequest) (*GetAllMovieDetailsResponse, error)
	GetAllAnimeDetails(context.Context, *GetAllAnimeDetailsRequest) (*GetAllAnimeDetailsResponse, error)
	GetAllGameDetails(context.Context, *GetAllGameDetailsRequest) (*GetAllGameDetailsResponse, error)
	GetAllSeriesDetails(context.Context, *GetAllSeriesDetailsRequest) (*GetAllSeriesDetailsResponse, error)
	GetAllBookDetails(context.Context, *GetAllBookDetailsRequest) (*GetAllBookDetailsResponse, error)
	mustEmbedUnimplementedCatalogServiceServer()
}

// UnimplementedCatalogServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCatalogServiceServer struct{}

func (UnimplementedCatalogServiceServer) CreateContent(context.Context, *CreateContentRequest) (*CreateContentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateContent not implemented")
}
func (UnimplementedCatalogServiceServer) GetContent(context.Context, *GetContentRequest) (*GetContentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContent not implemented")
}
func (UnimplementedCatalogServiceServer) GetContentByIDs(context.Context, *GetContentByIDsRequest) (*GetContentByIDsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContentByIDs not implemented")
}
func (UnimplementedCatalogServiceServer) UpdateContent(context.Context, *UpdateContentRequest) (*UpdateContentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateContent not implemented")
}
func (UnimplementedCatalogServiceServer) FindContentByExternal(context.Context, *FindContentByExternalRequest) (*FindContentByExternalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindContentByExternal not implemented")
}
func (UnimplementedCatalogServiceServer) GetMovieDetails(context.Context, *GetMovieDetailsRequest) (*GetMovieDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMovieDetails not implemented")
}
func (UnimplementedCatalogServiceServer) GetAnimeDetails(context.Context, *GetAnimeDetailsRequest) (*GetAnimeDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAnimeDetails not implemented")
}
func (UnimplementedCatalogServiceServer) GetGameDetails(context.Context, *GetGameDetailsRequest) (*GetGameDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGameDetails not implemented")
}
func (UnimplementedCatalogServiceServer) GetSeriesDetails(context.Context, *GetSeriesDetailsRequest) (*GetSeriesDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSeriesDetails not implemented")
}
func (UnimplementedCatalogServiceServer) GetBookDetails(context.Context, *GetBookDetailsRequest) (*GetBookDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBookDetails not implemented")
}
func (UnimplementedCatalogServiceServer) GetAllMovieDetails(context.Context, *GetAllMovieDetailsRequest) (*GetAllMovieDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllMovieDetails not implemented")
}
func (UnimplementedCatalogServiceServer) GetAllAnimeDetails(context.Context, *GetAllAnimeDetailsRequest) (*GetAllAnimeDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllAnimeDetails not implemented")
}
func (UnimplementedCatalogServiceServer) GetAllGameDetails(context.Context, *GetAllGameDetailsRequest) (*GetAllGameDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllGameDetails not implemented")
}
func (UnimplementedCatalogServiceServer) GetAllSeriesDetails(context.Context, *GetAllSeriesDetailsRequest) (*GetAllSeriesDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllSeriesDetails not implemented")
}
func (UnimplementedCatalogServiceServer) GetAllBookDetails(context.Context, *GetAllBookDetailsRequest) (*GetAllBookDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllBookDetails not implemented")
}
func (UnimplementedCatalogServiceServer) mustEmbedUnimplementedCatalogServiceServer() {}
func (UnimplementedCatalogServiceServer) testEmbeddedByValue()                        {}

// UnsafeCatalogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CatalogServiceServer will
// result in compilation errors.
type UnsafeCatalogServiceServer interface {
	mustEmbedUnimplementedCatalogServiceServer()
}

func RegisterCatalogServiceServer(s grpc.ServiceRegistrar, srv CatalogServiceServer) {
	// If the following call pancis, it indicates UnimplementedCatalogServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CatalogService_ServiceDesc, srv)
}

func _CatalogService_CreateContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).CreateContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_CreateContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).CreateContent(ctx, req.(*CreateContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetContent(ctx, req.(*GetContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetContentByIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContentByIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetContentByIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetContentByIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetContentByIDs(ctx, req.(*GetContentByIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_UpdateContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).UpdateContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_UpdateContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).UpdateContent(ctx, req.(*UpdateContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_FindContentByExternal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindContentByExternalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).FindContentByExternal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_FindContentByExternal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).FindContentByExternal(ctx, req.(*FindContentByExternalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetMovieDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMovieDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetMovieDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetMovieDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetMovieDetails(ctx, req.(*GetMovieDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetAnimeDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAnimeDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetAnimeDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetAnimeDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetAnimeDetails(ctx, req.(*GetAnimeDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetGameDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGameDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetGameDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetGameDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetGameDetails(ctx, req.(*GetGameDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetSeriesDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSeriesDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetSeriesDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetSeriesDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetSeriesDetails(ctx, req.(*GetSeriesDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetBookDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBookDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetBookDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetBookDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetBookDetails(ctx, req.(*GetBookDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetAllMovieDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllMovieDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetAllMovieDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetAllMovieDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetAllMovieDetails(ctx, req.(*GetAllMovieDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetAllAnimeDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllAnimeDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetAllAnimeDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetAllAnimeDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetAllAnimeDetails(ctx, req.(*GetAllAnimeDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetAllGameDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllGameDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetAllGameDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetAllGameDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetAllGameDetails(ctx, req.(*GetAllGameDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetAllSeriesDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllSeriesDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetAllSeriesDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetAllSeriesDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetAllSeriesDetails(ctx, req.(*GetAllSeriesDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetAllBookDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllBookDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetAllBookDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetAllBookDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetAllBookDetails(ctx, req.(*GetAllBookDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CatalogService_ServiceDesc is the grpc.ServiceDesc for CatalogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CatalogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "catalog.CatalogService",
	HandlerType: (*CatalogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateContent",
			Handler:    _CatalogService_CreateContent_Handler,
		},
		{
			MethodName: "GetContent",
			Handler:    _CatalogService_GetContent_Handler,
		},
		{
			MethodName: "GetContentByIDs",
			Handler:    _CatalogService_GetContentByIDs_Handler,
		},
		{
			MethodName: "UpdateContent",
			Handler:    _CatalogService_UpdateContent_Handler,
		},
		{
			MethodName: "FindContentByExternal",
			Handler:    _CatalogService_FindContentByExternal_Handler,
		},
		{
			MethodName: "GetMovieDetails",
			Handler:    _CatalogService_GetMovieDetails_Handler,
		},
		{
			MethodName: "GetAnimeDetails",
			Handler:    _CatalogService_GetAnimeDetails_Handler,
		},
		{
			MethodName: "GetGameDetails",
			Handler:    _CatalogService_GetGameDetails_Handler,
		},
		{
			MethodName: "GetSeriesDetails",
			Handler:    _CatalogService_GetSeriesDetails_Handler,
		},
		{
			MethodName: "GetBookDetails",
			Handler:    _CatalogService_GetBookDetails_Handler,
		},
		{
			MethodName: "GetAllMovieDetails",
			Handler:    _CatalogService_GetAllMovieDetails_Handler,
		},
		{
			MethodName: "GetAllAnimeDetails",
			Handler:    _CatalogService_GetAllAnimeDetails_Handler,
		},
		{
			MethodName: "GetAllGameDetails",
			Handler:    _CatalogService_GetAllGameDetails_Handler,
		},
		{
			MethodName: "GetAllSeriesDetails",
			Handler:    _CatalogService_GetAllSeriesDetails_Handler,
		},
		{
			MethodName: "GetAllBookDetails",
			Handler:    _CatalogService_GetAllBookDetails_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "catalog-system/catalog.proto",
}
