// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: rec-system/rec.proto

package recommendationpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserAction int32

const (
	UserAction_VIEW             UserAction = 0
	UserAction_LIKE             UserAction = 1
	UserAction_DISLIKE          UserAction = 2
	UserAction_RATE             UserAction = 3
	UserAction_ADD_TO_FAVORITES UserAction = 4
)

// Enum value maps for UserAction.
var (
	UserAction_name = map[int32]string{
		0: "VIEW",
		1: "LIKE",
		2: "DISLIKE",
		3: "RATE",
		4: "ADD_TO_FAVORITES",
	}
	UserAction_value = map[string]int32{
		"VIEW":             0,
		"LIKE":             1,
		"DISLIKE":          2,
		"RATE":             3,
		"ADD_TO_FAVORITES": 4,
	}
)

func (x UserAction) Enum() *UserAction {
	p := new(UserAction)
	*p = x
	return p
}

func (x UserAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserAction) Descriptor() protoreflect.EnumDescriptor {
	return file_rec_system_rec_proto_enumTypes[0].Descriptor()
}

func (UserAction) Type() protoreflect.EnumType {
	return &file_rec_system_rec_proto_enumTypes[0]
}

func (x UserAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserAction.Descriptor instead.
func (UserAction) EnumDescriptor() ([]byte, []int) {
	return file_rec_system_rec_proto_rawDescGZIP(), []int{0}
}

type RecommendationMode int32

const (
	RecommendationMode_IMPLICIT RecommendationMode = 0 // по истории пользователя
	RecommendationMode_EXPLICIT RecommendationMode = 1 // пользовательский ввод
)

// Enum value maps for RecommendationMode.
var (
	RecommendationMode_name = map[int32]string{
		0: "IMPLICIT",
		1: "EXPLICIT",
	}
	RecommendationMode_value = map[string]int32{
		"IMPLICIT": 0,
		"EXPLICIT": 1,
	}
)

func (x RecommendationMode) Enum() *RecommendationMode {
	p := new(RecommendationMode)
	*p = x
	return p
}

func (x RecommendationMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecommendationMode) Descriptor() protoreflect.EnumDescriptor {
	return file_rec_system_rec_proto_enumTypes[1].Descriptor()
}

func (RecommendationMode) Type() protoreflect.EnumType {
	return &file_rec_system_rec_proto_enumTypes[1]
}

func (x RecommendationMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RecommendationMode.Descriptor instead.
func (RecommendationMode) EnumDescriptor() ([]byte, []int) {
	return file_rec_system_rec_proto_rawDescGZIP(), []int{1}
}

//core
type GetRecommendationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecommendationsRequest) Reset() {
	*x = GetRecommendationsRequest{}
	mi := &file_rec_system_rec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendationsRequest) ProtoMessage() {}

func (x *GetRecommendationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rec_system_rec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendationsRequest.ProtoReflect.Descriptor instead.
func (*GetRecommendationsRequest) Descriptor() ([]byte, []int) {
	return file_rec_system_rec_proto_rawDescGZIP(), []int{0}
}

func (x *GetRecommendationsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetRecommendationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetRecommendationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentIds    []string               `protobuf:"bytes,1,rep,name=content_ids,json=contentIds,proto3" json:"content_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecommendationsResponse) Reset() {
	*x = GetRecommendationsResponse{}
	mi := &file_rec_system_rec_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendationsResponse) ProtoMessage() {}

func (x *GetRecommendationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rec_system_rec_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendationsResponse.ProtoReflect.Descriptor instead.
func (*GetRecommendationsResponse) Descriptor() ([]byte, []int) {
	return file_rec_system_rec_proto_rawDescGZIP(), []int{1}
}

func (x *GetRecommendationsResponse) GetContentIds() []string {
	if x != nil {
		return x.ContentIds
	}
	return nil
}

type GetRecommendationsByGenresRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Genres        []string               `protobuf:"bytes,1,rep,name=genres,proto3" json:"genres,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecommendationsByGenresRequest) Reset() {
	*x = GetRecommendationsByGenresRequest{}
	mi := &file_rec_system_rec_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendationsByGenresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendationsByGenresRequest) ProtoMessage() {}

func (x *GetRecommendationsByGenresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rec_system_rec_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendationsByGenresRequest.ProtoReflect.Descriptor instead.
func (*GetRecommendationsByGenresRequest) Descriptor() ([]byte, []int) {
	return file_rec_system_rec_proto_rawDescGZIP(), []int{2}
}

func (x *GetRecommendationsByGenresRequest) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *GetRecommendationsByGenresRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetRecommendationsByGenresResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentIds    []string               `protobuf:"bytes,1,rep,name=content_ids,json=contentIds,proto3" json:"content_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecommendationsByGenresResponse) Reset() {
	*x = GetRecommendationsByGenresResponse{}
	mi := &file_rec_system_rec_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendationsByGenresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendationsByGenresResponse) ProtoMessage() {}

func (x *GetRecommendationsByGenresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rec_system_rec_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendationsByGenresResponse.ProtoReflect.Descriptor instead.
func (*GetRecommendationsByGenresResponse) Descriptor() ([]byte, []int) {
	return file_rec_system_rec_proto_rawDescGZIP(), []int{3}
}

func (x *GetRecommendationsByGenresResponse) GetContentIds() []string {
	if x != nil {
		return x.ContentIds
	}
	return nil
}

type TrackUserActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackUserActionResponse) Reset() {
	*x = TrackUserActionResponse{}
	mi := &file_rec_system_rec_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackUserActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackUserActionResponse) ProtoMessage() {}

func (x *TrackUserActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rec_system_rec_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackUserActionResponse.ProtoReflect.Descriptor instead.
func (*TrackUserActionResponse) Descriptor() ([]byte, []int) {
	return file_rec_system_rec_proto_rawDescGZIP(), []int{4}
}

type TrackUserActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ContentId     string                 `protobuf:"bytes,2,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	Action        UserAction             `protobuf:"varint,3,opt,name=action,proto3,enum=recommendation.UserAction" json:"action,omitempty"`
	Rating        *int32                 `protobuf:"varint,4,opt,name=rating,proto3,oneof" json:"rating,omitempty"`
	DurationSec   *int32                 `protobuf:"varint,5,opt,name=duration_sec,json=durationSec,proto3,oneof" json:"duration_sec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackUserActionRequest) Reset() {
	*x = TrackUserActionRequest{}
	mi := &file_rec_system_rec_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackUserActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackUserActionRequest) ProtoMessage() {}

func (x *TrackUserActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rec_system_rec_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackUserActionRequest.ProtoReflect.Descriptor instead.
func (*TrackUserActionRequest) Descriptor() ([]byte, []int) {
	return file_rec_system_rec_proto_rawDescGZIP(), []int{5}
}

func (x *TrackUserActionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TrackUserActionRequest) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *TrackUserActionRequest) GetAction() UserAction {
	if x != nil {
		return x.Action
	}
	return UserAction_VIEW
}

func (x *TrackUserActionRequest) GetRating() int32 {
	if x != nil && x.Rating != nil {
		return *x.Rating
	}
	return 0
}

func (x *TrackUserActionRequest) GetDurationSec() int32 {
	if x != nil && x.DurationSec != nil {
		return *x.DurationSec
	}
	return 0
}

type GetSimilarContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSimilarContentRequest) Reset() {
	*x = GetSimilarContentRequest{}
	mi := &file_rec_system_rec_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSimilarContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSimilarContentRequest) ProtoMessage() {}

func (x *GetSimilarContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rec_system_rec_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSimilarContentRequest.ProtoReflect.Descriptor instead.
func (*GetSimilarContentRequest) Descriptor() ([]byte, []int) {
	return file_rec_system_rec_proto_rawDescGZIP(), []int{6}
}

func (x *GetSimilarContentRequest) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *GetSimilarContentRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetSimilarContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentIds    []string               `protobuf:"bytes,1,rep,name=content_ids,json=contentIds,proto3" json:"content_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSimilarContentResponse) Reset() {
	*x = GetSimilarContentResponse{}
	mi := &file_rec_system_rec_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSimilarContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSimilarContentResponse) ProtoMessage() {}

func (x *GetSimilarContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rec_system_rec_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSimilarContentResponse.ProtoReflect.Descriptor instead.
func (*GetSimilarContentResponse) Descriptor() ([]byte, []int) {
	return file_rec_system_rec_proto_rawDescGZIP(), []int{7}
}

func (x *GetSimilarContentResponse) GetContentIds() []string {
	if x != nil {
		return x.ContentIds
	}
	return nil
}

type GetTrendingContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrendingContentRequest) Reset() {
	*x = GetTrendingContentRequest{}
	mi := &file_rec_system_rec_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrendingContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrendingContentRequest) ProtoMessage() {}

func (x *GetTrendingContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rec_system_rec_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrendingContentRequest.ProtoReflect.Descriptor instead.
func (*GetTrendingContentRequest) Descriptor() ([]byte, []int) {
	return file_rec_system_rec_proto_rawDescGZIP(), []int{8}
}

func (x *GetTrendingContentRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetTrendingContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentIds    []string               `protobuf:"bytes,1,rep,name=content_ids,json=contentIds,proto3" json:"content_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrendingContentResponse) Reset() {
	*x = GetTrendingContentResponse{}
	mi := &file_rec_system_rec_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrendingContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrendingContentResponse) ProtoMessage() {}

func (x *GetTrendingContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rec_system_rec_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrendingContentResponse.ProtoReflect.Descriptor instead.
func (*GetTrendingContentResponse) Descriptor() ([]byte, []int) {
	return file_rec_system_rec_proto_rawDescGZIP(), []int{9}
}

func (x *GetTrendingContentResponse) GetContentIds() []string {
	if x != nil {
		return x.ContentIds
	}
	return nil
}

// preferences
type GetUserPreferencesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPreferencesRequest) Reset() {
	*x = GetUserPreferencesRequest{}
	mi := &file_rec_system_rec_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPreferencesRequest) ProtoMessage() {}

func (x *GetUserPreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rec_system_rec_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPreferencesRequest.ProtoReflect.Descriptor instead.
func (*GetUserPreferencesRequest) Descriptor() ([]byte, []int) {
	return file_rec_system_rec_proto_rawDescGZIP(), []int{10}
}

func (x *GetUserPreferencesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserPreferencesResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PreferredGenres []string               `protobuf:"bytes,1,rep,name=preferred_genres,json=preferredGenres,proto3" json:"preferred_genres,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetUserPreferencesResponse) Reset() {
	*x = GetUserPreferencesResponse{}
	mi := &file_rec_system_rec_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPreferencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPreferencesResponse) ProtoMessage() {}

func (x *GetUserPreferencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rec_system_rec_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPreferencesResponse.ProtoReflect.Descriptor instead.
func (*GetUserPreferencesResponse) Descriptor() ([]byte, []int) {
	return file_rec_system_rec_proto_rawDescGZIP(), []int{11}
}

func (x *GetUserPreferencesResponse) GetPreferredGenres() []string {
	if x != nil {
		return x.PreferredGenres
	}
	return nil
}

type SetUserPreferencesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PreferredGenres []string               `protobuf:"bytes,2,rep,name=preferred_genres,json=preferredGenres,proto3" json:"preferred_genres,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SetUserPreferencesRequest) Reset() {
	*x = SetUserPreferencesRequest{}
	mi := &file_rec_system_rec_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserPreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserPreferencesRequest) ProtoMessage() {}

func (x *SetUserPreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rec_system_rec_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserPreferencesRequest.ProtoReflect.Descriptor instead.
func (*SetUserPreferencesRequest) Descriptor() ([]byte, []int) {
	return file_rec_system_rec_proto_rawDescGZIP(), []int{12}
}

func (x *SetUserPreferencesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SetUserPreferencesRequest) GetPreferredGenres() []string {
	if x != nil {
		return x.PreferredGenres
	}
	return nil
}

type SetUserPreferencesResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	UserPreferencesSetted bool                   `protobuf:"varint,1,opt,name=UserPreferencesSetted,proto3" json:"UserPreferencesSetted,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SetUserPreferencesResponse) Reset() {
	*x = SetUserPreferencesResponse{}
	mi := &file_rec_system_rec_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserPreferencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserPreferencesResponse) ProtoMessage() {}

func (x *SetUserPreferencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rec_system_rec_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserPreferencesResponse.ProtoReflect.Descriptor instead.
func (*SetUserPreferencesResponse) Descriptor() ([]byte, []int) {
	return file_rec_system_rec_proto_rawDescGZIP(), []int{13}
}

func (x *SetUserPreferencesResponse) GetUserPreferencesSetted() bool {
	if x != nil {
		return x.UserPreferencesSetted
	}
	return false
}

type ResetUserPreferencesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetUserPreferencesRequest) Reset() {
	*x = ResetUserPreferencesRequest{}
	mi := &file_rec_system_rec_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetUserPreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetUserPreferencesRequest) ProtoMessage() {}

func (x *ResetUserPreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rec_system_rec_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetUserPreferencesRequest.ProtoReflect.Descriptor instead.
func (*ResetUserPreferencesRequest) Descriptor() ([]byte, []int) {
	return file_rec_system_rec_proto_rawDescGZIP(), []int{14}
}

func (x *ResetUserPreferencesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ResetUserPreferencesResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	UserPreferencesResetted bool                   `protobuf:"varint,1,opt,name=UserPreferencesResetted,proto3" json:"UserPreferencesResetted,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ResetUserPreferencesResponse) Reset() {
	*x = ResetUserPreferencesResponse{}
	mi := &file_rec_system_rec_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetUserPreferencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetUserPreferencesResponse) ProtoMessage() {}

func (x *ResetUserPreferencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rec_system_rec_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetUserPreferencesResponse.ProtoReflect.Descriptor instead.
func (*ResetUserPreferencesResponse) Descriptor() ([]byte, []int) {
	return file_rec_system_rec_proto_rawDescGZIP(), []int{15}
}

func (x *ResetUserPreferencesResponse) GetUserPreferencesResetted() bool {
	if x != nil {
		return x.UserPreferencesResetted
	}
	return false
}

type RebuildUserPreferencesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebuildUserPreferencesRequest) Reset() {
	*x = RebuildUserPreferencesRequest{}
	mi := &file_rec_system_rec_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebuildUserPreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebuildUserPreferencesRequest) ProtoMessage() {}

func (x *RebuildUserPreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rec_system_rec_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebuildUserPreferencesRequest.ProtoReflect.Descriptor instead.
func (*RebuildUserPreferencesRequest) Descriptor() ([]byte, []int) {
	return file_rec_system_rec_proto_rawDescGZIP(), []int{16}
}

func (x *RebuildUserPreferencesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RebuildUserPreferencesResponce struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebuildUserPreferencesResponce) Reset() {
	*x = RebuildUserPreferencesResponce{}
	mi := &file_rec_system_rec_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebuildUserPreferencesResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebuildUserPreferencesResponce) ProtoMessage() {}

func (x *RebuildUserPreferencesResponce) ProtoReflect() protoreflect.Message {
	mi := &file_rec_system_rec_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebuildUserPreferencesResponce.ProtoReflect.Descriptor instead.
func (*RebuildUserPreferencesResponce) Descriptor() ([]byte, []int) {
	return file_rec_system_rec_proto_rawDescGZIP(), []int{17}
}

// cold start
type GetPopularContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPopularContentRequest) Reset() {
	*x = GetPopularContentRequest{}
	mi := &file_rec_system_rec_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPopularContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPopularContentRequest) ProtoMessage() {}

func (x *GetPopularContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rec_system_rec_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPopularContentRequest.ProtoReflect.Descriptor instead.
func (*GetPopularContentRequest) Descriptor() ([]byte, []int) {
	return file_rec_system_rec_proto_rawDescGZIP(), []int{18}
}

func (x *GetPopularContentRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetPopularContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentIds    []string               `protobuf:"bytes,1,rep,name=content_ids,json=contentIds,proto3" json:"content_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPopularContentResponse) Reset() {
	*x = GetPopularContentResponse{}
	mi := &file_rec_system_rec_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPopularContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPopularContentResponse) ProtoMessage() {}

func (x *GetPopularContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rec_system_rec_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPopularContentResponse.ProtoReflect.Descriptor instead.
func (*GetPopularContentResponse) Descriptor() ([]byte, []int) {
	return file_rec_system_rec_proto_rawDescGZIP(), []int{19}
}

func (x *GetPopularContentResponse) GetContentIds() []string {
	if x != nil {
		return x.ContentIds
	}
	return nil
}

type GetAIRecommendationsRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	UserId string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Mode   RecommendationMode     `protobuf:"varint,2,opt,name=mode,proto3,enum=recommendation.RecommendationMode" json:"mode,omitempty"`
	// Только для EXPLICIT
	Query         *string `protobuf:"bytes,3,opt,name=query,proto3,oneof" json:"query,omitempty"`
	Limit         int32   `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAIRecommendationsRequest) Reset() {
	*x = GetAIRecommendationsRequest{}
	mi := &file_rec_system_rec_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAIRecommendationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAIRecommendationsRequest) ProtoMessage() {}

func (x *GetAIRecommendationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rec_system_rec_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAIRecommendationsRequest.ProtoReflect.Descriptor instead.
func (*GetAIRecommendationsRequest) Descriptor() ([]byte, []int) {
	return file_rec_system_rec_proto_rawDescGZIP(), []int{20}
}

func (x *GetAIRecommendationsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetAIRecommendationsRequest) GetMode() RecommendationMode {
	if x != nil {
		return x.Mode
	}
	return RecommendationMode_IMPLICIT
}

func (x *GetAIRecommendationsRequest) GetQuery() string {
	if x != nil && x.Query != nil {
		return *x.Query
	}
	return ""
}

func (x *GetAIRecommendationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetAIRecommendationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentIds    []string               `protobuf:"bytes,1,rep,name=content_ids,json=contentIds,proto3" json:"content_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAIRecommendationsResponse) Reset() {
	*x = GetAIRecommendationsResponse{}
	mi := &file_rec_system_rec_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAIRecommendationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAIRecommendationsResponse) ProtoMessage() {}

func (x *GetAIRecommendationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rec_system_rec_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAIRecommendationsResponse.ProtoReflect.Descriptor instead.
func (*GetAIRecommendationsResponse) Descriptor() ([]byte, []int) {
	return file_rec_system_rec_proto_rawDescGZIP(), []int{21}
}

func (x *GetAIRecommendationsResponse) GetContentIds() []string {
	if x != nil {
		return x.ContentIds
	}
	return nil
}

var File_rec_system_rec_proto protoreflect.FileDescriptor

const file_rec_system_rec_proto_rawDesc = "" +
	"\n" +
	"\x14rec-system/rec.proto\x12\x0erecommendation\"J\n" +
	"\x19GetRecommendationsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"=\n" +
	"\x1aGetRecommendationsResponse\x12\x1f\n" +
	"\vcontent_ids\x18\x01 \x03(\tR\n" +
	"contentIds\"Q\n" +
	"!GetRecommendationsByGenresRequest\x12\x16\n" +
	"\x06genres\x18\x01 \x03(\tR\x06genres\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"E\n" +
	"\"GetRecommendationsByGenresResponse\x12\x1f\n" +
	"\vcontent_ids\x18\x01 \x03(\tR\n" +
	"contentIds\"\x19\n" +
	"\x17TrackUserActionResponse\"\xe5\x01\n" +
	"\x16TrackUserActionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"content_id\x18\x02 \x01(\tR\tcontentId\x122\n" +
	"\x06action\x18\x03 \x01(\x0e2\x1a.recommendation.UserActionR\x06action\x12\x1b\n" +
	"\x06rating\x18\x04 \x01(\x05H\x00R\x06rating\x88\x01\x01\x12&\n" +
	"\fduration_sec\x18\x05 \x01(\x05H\x01R\vdurationSec\x88\x01\x01B\t\n" +
	"\a_ratingB\x0f\n" +
	"\r_duration_sec\"O\n" +
	"\x18GetSimilarContentRequest\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"<\n" +
	"\x19GetSimilarContentResponse\x12\x1f\n" +
	"\vcontent_ids\x18\x01 \x03(\tR\n" +
	"contentIds\"1\n" +
	"\x19GetTrendingContentRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"=\n" +
	"\x1aGetTrendingContentResponse\x12\x1f\n" +
	"\vcontent_ids\x18\x01 \x03(\tR\n" +
	"contentIds\"4\n" +
	"\x19GetUserPreferencesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"G\n" +
	"\x1aGetUserPreferencesResponse\x12)\n" +
	"\x10preferred_genres\x18\x01 \x03(\tR\x0fpreferredGenres\"_\n" +
	"\x19SetUserPreferencesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12)\n" +
	"\x10preferred_genres\x18\x02 \x03(\tR\x0fpreferredGenres\"R\n" +
	"\x1aSetUserPreferencesResponse\x124\n" +
	"\x15UserPreferencesSetted\x18\x01 \x01(\bR\x15UserPreferencesSetted\"6\n" +
	"\x1bResetUserPreferencesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"X\n" +
	"\x1cResetUserPreferencesResponse\x128\n" +
	"\x17UserPreferencesResetted\x18\x01 \x01(\bR\x17UserPreferencesResetted\"8\n" +
	"\x1dRebuildUserPreferencesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\" \n" +
	"\x1eRebuildUserPreferencesResponce\"0\n" +
	"\x18GetPopularContentRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"<\n" +
	"\x19GetPopularContentResponse\x12\x1f\n" +
	"\vcontent_ids\x18\x01 \x03(\tR\n" +
	"contentIds\"\xa9\x01\n" +
	"\x1bGetAIRecommendationsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x126\n" +
	"\x04mode\x18\x02 \x01(\x0e2\".recommendation.RecommendationModeR\x04mode\x12\x19\n" +
	"\x05query\x18\x03 \x01(\tH\x00R\x05query\x88\x01\x01\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limitB\b\n" +
	"\x06_query\"?\n" +
	"\x1cGetAIRecommendationsResponse\x12\x1f\n" +
	"\vcontent_ids\x18\x01 \x03(\tR\n" +
	"contentIds*M\n" +
	"\n" +
	"UserAction\x12\b\n" +
	"\x04VIEW\x10\x00\x12\b\n" +
	"\x04LIKE\x10\x01\x12\v\n" +
	"\aDISLIKE\x10\x02\x12\b\n" +
	"\x04RATE\x10\x03\x12\x14\n" +
	"\x10ADD_TO_FAVORITES\x10\x04*0\n" +
	"\x12RecommendationMode\x12\f\n" +
	"\bIMPLICIT\x10\x00\x12\f\n" +
	"\bEXPLICIT\x10\x012\xe8\t\n" +
	"\x15RecommendationService\x12k\n" +
	"\x12GetRecommendations\x12).recommendation.GetRecommendationsRequest\x1a*.recommendation.GetRecommendationsResponse\x12b\n" +
	"\x0fTrackUserAction\x12&.recommendation.TrackUserActionRequest\x1a'.recommendation.TrackUserActionResponse\x12q\n" +
	"\x14GetAIRecommendations\x12+.recommendation.GetAIRecommendationsRequest\x1a,.recommendation.GetAIRecommendationsResponse\x12\x83\x01\n" +
	"\x1aGetRecommendationsByGenres\x121.recommendation.GetRecommendationsByGenresRequest\x1a2.recommendation.GetRecommendationsByGenresResponse\x12h\n" +
	"\x11GetSimilarContent\x12(.recommendation.GetSimilarContentRequest\x1a).recommendation.GetSimilarContentResponse\x12k\n" +
	"\x12GetTrendingContent\x12).recommendation.GetTrendingContentRequest\x1a*.recommendation.GetTrendingContentResponse\x12k\n" +
	"\x12GetUserPreferences\x12).recommendation.GetUserPreferencesRequest\x1a*.recommendation.GetUserPreferencesResponse\x12k\n" +
	"\x12SetUserPreferences\x12).recommendation.SetUserPreferencesRequest\x1a*.recommendation.SetUserPreferencesResponse\x12q\n" +
	"\x14ResetUserPreferences\x12+.recommendation.ResetUserPreferencesRequest\x1a,.recommendation.ResetUserPreferencesResponse\x12w\n" +
	"\x16RebuildUserPreferences\x12-.recommendation.RebuildUserPreferencesRequest\x1a..recommendation.RebuildUserPreferencesResponce\x12h\n" +
	"\x11GetPopularContent\x12(.recommendation.GetPopularContentRequest\x1a).recommendation.GetPopularContentResponseBEZCrec-system-microservice/internal/pb/recommendation;recommendationpbb\x06proto3"

var (
	file_rec_system_rec_proto_rawDescOnce sync.Once
	file_rec_system_rec_proto_rawDescData []byte
)

func file_rec_system_rec_proto_rawDescGZIP() []byte {
	file_rec_system_rec_proto_rawDescOnce.Do(func() {
		file_rec_system_rec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rec_system_rec_proto_rawDesc), len(file_rec_system_rec_proto_rawDesc)))
	})
	return file_rec_system_rec_proto_rawDescData
}

var file_rec_system_rec_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_rec_system_rec_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_rec_system_rec_proto_goTypes = []any{
	(UserAction)(0),                            // 0: recommendation.UserAction
	(RecommendationMode)(0),                    // 1: recommendation.RecommendationMode
	(*GetRecommendationsRequest)(nil),          // 2: recommendation.GetRecommendationsRequest
	(*GetRecommendationsResponse)(nil),         // 3: recommendation.GetRecommendationsResponse
	(*GetRecommendationsByGenresRequest)(nil),  // 4: recommendation.GetRecommendationsByGenresRequest
	(*GetRecommendationsByGenresResponse)(nil), // 5: recommendation.GetRecommendationsByGenresResponse
	(*TrackUserActionResponse)(nil),            // 6: recommendation.TrackUserActionResponse
	(*TrackUserActionRequest)(nil),             // 7: recommendation.TrackUserActionRequest
	(*GetSimilarContentRequest)(nil),           // 8: recommendation.GetSimilarContentRequest
	(*GetSimilarContentResponse)(nil),          // 9: recommendation.GetSimilarContentResponse
	(*GetTrendingContentRequest)(nil),          // 10: recommendation.GetTrendingContentRequest
	(*GetTrendingContentResponse)(nil),         // 11: recommendation.GetTrendingContentResponse
	(*GetUserPreferencesRequest)(nil),          // 12: recommendation.GetUserPreferencesRequest
	(*GetUserPreferencesResponse)(nil),         // 13: recommendation.GetUserPreferencesResponse
	(*SetUserPreferencesRequest)(nil),          // 14: recommendation.SetUserPreferencesRequest
	(*SetUserPreferencesResponse)(nil),         // 15: recommendation.SetUserPreferencesResponse
	(*ResetUserPreferencesRequest)(nil),        // 16: recommendation.ResetUserPreferencesRequest
	(*ResetUserPreferencesResponse)(nil),       // 17: recommendation.ResetUserPreferencesResponse
	(*RebuildUserPreferencesRequest)(nil),      // 18: recommendation.RebuildUserPreferencesRequest
	(*RebuildUserPreferencesResponce)(nil),     // 19: recommendation.RebuildUserPreferencesResponce
	(*GetPopularContentRequest)(nil),           // 20: recommendation.GetPopularContentRequest
	(*GetPopularContentResponse)(nil),          // 21: recommendation.GetPopularContentResponse
	(*GetAIRecommendationsRequest)(nil),        // 22: recommendation.GetAIRecommendationsRequest
	(*GetAIRecommendationsResponse)(nil),       // 23: recommendation.GetAIRecommendationsResponse
}
var file_rec_system_rec_proto_depIdxs = []int32{
	0,  // 0: recommendation.TrackUserActionRequest.action:type_name -> recommendation.UserAction
	1,  // 1: recommendation.GetAIRecommendationsRequest.mode:type_name -> recommendation.RecommendationMode
	2,  // 2: recommendation.RecommendationService.GetRecommendations:input_type -> recommendation.GetRecommendationsRequest
	7,  // 3: recommendation.RecommendationService.TrackUserAction:input_type -> recommendation.TrackUserActionRequest
	22, // 4: recommendation.RecommendationService.GetAIRecommendations:input_type -> recommendation.GetAIRecommendationsRequest
	4,  // 5: recommendation.RecommendationService.GetRecommendationsByGenres:input_type -> recommendation.GetRecommendationsByGenresRequest
	8,  // 6: recommendation.RecommendationService.GetSimilarContent:input_type -> recommendation.GetSimilarContentRequest
	10, // 7: recommendation.RecommendationService.GetTrendingContent:input_type -> recommendation.GetTrendingContentRequest
	12, // 8: recommendation.RecommendationService.GetUserPreferences:input_type -> recommendation.GetUserPreferencesRequest
	14, // 9: recommendation.RecommendationService.SetUserPreferences:input_type -> recommendation.SetUserPreferencesRequest
	16, // 10: recommendation.RecommendationService.ResetUserPreferences:input_type -> recommendation.ResetUserPreferencesRequest
	18, // 11: recommendation.RecommendationService.RebuildUserPreferences:input_type -> recommendation.RebuildUserPreferencesRequest
	20, // 12: recommendation.RecommendationService.GetPopularContent:input_type -> recommendation.GetPopularContentRequest
	3,  // 13: recommendation.RecommendationService.GetRecommendations:output_type -> recommendation.GetRecommendationsResponse
	6,  // 14: recommendation.RecommendationService.TrackUserAction:output_type -> recommendation.TrackUserActionResponse
	23, // 15: recommendation.RecommendationService.GetAIRecommendations:output_type -> recommendation.GetAIRecommendationsResponse
	5,  // 16: recommendation.RecommendationService.GetRecommendationsByGenres:output_type -> recommendation.GetRecommendationsByGenresResponse
	9,  // 17: recommendation.RecommendationService.GetSimilarContent:output_type -> recommendation.GetSimilarContentResponse
	11, // 18: recommendation.RecommendationService.GetTrendingContent:output_type -> recommendation.GetTrendingContentResponse
	13, // 19: recommendation.RecommendationService.GetUserPreferences:output_type -> recommendation.GetUserPreferencesResponse
	15, // 20: recommendation.RecommendationService.SetUserPreferences:output_type -> recommendation.SetUserPreferencesResponse
	17, // 21: recommendation.RecommendationService.ResetUserPreferences:output_type -> recommendation.ResetUserPreferencesResponse
	19, // 22: recommendation.RecommendationService.RebuildUserPreferences:output_type -> recommendation.RebuildUserPreferencesResponce
	21, // 23: recommendation.RecommendationService.GetPopularContent:output_type -> recommendation.GetPopularContentResponse
	13, // [13:24] is the sub-list for method output_type
	2,  // [2:13] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_rec_system_rec_proto_init() }
func file_rec_system_rec_proto_init() {
	if File_rec_system_rec_proto != nil {
		return
	}
	file_rec_system_rec_proto_msgTypes[5].OneofWrappers = []any{}
	file_rec_system_rec_proto_msgTypes[20].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rec_system_rec_proto_rawDesc), len(file_rec_system_rec_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rec_system_rec_proto_goTypes,
		DependencyIndexes: file_rec_system_rec_proto_depIdxs,
		EnumInfos:         file_rec_system_rec_proto_enumTypes,
		MessageInfos:      file_rec_system_rec_proto_msgTypes,
	}.Build()
	File_rec_system_rec_proto = out.File
	file_rec_system_rec_proto_goTypes = nil
	file_rec_system_rec_proto_depIdxs = nil
}
