// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: rec-system/rec.proto

package recommendationpb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetRecommendationsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetRecommendationsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetRecommendationsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetRecommendationsRequestMultiError, or nil if none found.
func (m *GetRecommendationsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetRecommendationsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	// no validation rules for Limit

	if len(errors) > 0 {
		return GetRecommendationsRequestMultiError(errors)
	}

	return nil
}

// GetRecommendationsRequestMultiError is an error wrapping multiple validation
// errors returned by GetRecommendationsRequest.ValidateAll() if the
// designated constraints aren't met.
type GetRecommendationsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetRecommendationsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetRecommendationsRequestMultiError) AllErrors() []error { return m }

// GetRecommendationsRequestValidationError is the validation error returned by
// GetRecommendationsRequest.Validate if the designated constraints aren't met.
type GetRecommendationsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetRecommendationsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetRecommendationsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetRecommendationsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetRecommendationsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetRecommendationsRequestValidationError) ErrorName() string {
	return "GetRecommendationsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetRecommendationsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetRecommendationsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetRecommendationsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetRecommendationsRequestValidationError{}

// Validate checks the field values on GetRecommendationsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetRecommendationsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetRecommendationsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetRecommendationsResponseMultiError, or nil if none found.
func (m *GetRecommendationsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetRecommendationsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetRecommendationsResponseMultiError(errors)
	}

	return nil
}

// GetRecommendationsResponseMultiError is an error wrapping multiple
// validation errors returned by GetRecommendationsResponse.ValidateAll() if
// the designated constraints aren't met.
type GetRecommendationsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetRecommendationsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetRecommendationsResponseMultiError) AllErrors() []error { return m }

// GetRecommendationsResponseValidationError is the validation error returned
// by GetRecommendationsResponse.Validate if the designated constraints aren't met.
type GetRecommendationsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetRecommendationsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetRecommendationsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetRecommendationsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetRecommendationsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetRecommendationsResponseValidationError) ErrorName() string {
	return "GetRecommendationsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetRecommendationsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetRecommendationsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetRecommendationsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetRecommendationsResponseValidationError{}

// Validate checks the field values on GetRecommendationsByGenresRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *GetRecommendationsByGenresRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetRecommendationsByGenresRequest
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// GetRecommendationsByGenresRequestMultiError, or nil if none found.
func (m *GetRecommendationsByGenresRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetRecommendationsByGenresRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Limit

	if len(errors) > 0 {
		return GetRecommendationsByGenresRequestMultiError(errors)
	}

	return nil
}

// GetRecommendationsByGenresRequestMultiError is an error wrapping multiple
// validation errors returned by
// GetRecommendationsByGenresRequest.ValidateAll() if the designated
// constraints aren't met.
type GetRecommendationsByGenresRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetRecommendationsByGenresRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetRecommendationsByGenresRequestMultiError) AllErrors() []error { return m }

// GetRecommendationsByGenresRequestValidationError is the validation error
// returned by GetRecommendationsByGenresRequest.Validate if the designated
// constraints aren't met.
type GetRecommendationsByGenresRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetRecommendationsByGenresRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetRecommendationsByGenresRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetRecommendationsByGenresRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetRecommendationsByGenresRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetRecommendationsByGenresRequestValidationError) ErrorName() string {
	return "GetRecommendationsByGenresRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetRecommendationsByGenresRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetRecommendationsByGenresRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetRecommendationsByGenresRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetRecommendationsByGenresRequestValidationError{}

// Validate checks the field values on GetRecommendationsByGenresResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *GetRecommendationsByGenresResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetRecommendationsByGenresResponse
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// GetRecommendationsByGenresResponseMultiError, or nil if none found.
func (m *GetRecommendationsByGenresResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetRecommendationsByGenresResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetRecommendationsByGenresResponseMultiError(errors)
	}

	return nil
}

// GetRecommendationsByGenresResponseMultiError is an error wrapping multiple
// validation errors returned by
// GetRecommendationsByGenresResponse.ValidateAll() if the designated
// constraints aren't met.
type GetRecommendationsByGenresResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetRecommendationsByGenresResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetRecommendationsByGenresResponseMultiError) AllErrors() []error { return m }

// GetRecommendationsByGenresResponseValidationError is the validation error
// returned by GetRecommendationsByGenresResponse.Validate if the designated
// constraints aren't met.
type GetRecommendationsByGenresResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetRecommendationsByGenresResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetRecommendationsByGenresResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetRecommendationsByGenresResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetRecommendationsByGenresResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetRecommendationsByGenresResponseValidationError) ErrorName() string {
	return "GetRecommendationsByGenresResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetRecommendationsByGenresResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetRecommendationsByGenresResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetRecommendationsByGenresResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetRecommendationsByGenresResponseValidationError{}

// Validate checks the field values on TrackUserActionResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *TrackUserActionResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TrackUserActionResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TrackUserActionResponseMultiError, or nil if none found.
func (m *TrackUserActionResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *TrackUserActionResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return TrackUserActionResponseMultiError(errors)
	}

	return nil
}

// TrackUserActionResponseMultiError is an error wrapping multiple validation
// errors returned by TrackUserActionResponse.ValidateAll() if the designated
// constraints aren't met.
type TrackUserActionResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TrackUserActionResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TrackUserActionResponseMultiError) AllErrors() []error { return m }

// TrackUserActionResponseValidationError is the validation error returned by
// TrackUserActionResponse.Validate if the designated constraints aren't met.
type TrackUserActionResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TrackUserActionResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TrackUserActionResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TrackUserActionResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TrackUserActionResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TrackUserActionResponseValidationError) ErrorName() string {
	return "TrackUserActionResponseValidationError"
}

// Error satisfies the builtin error interface
func (e TrackUserActionResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTrackUserActionResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TrackUserActionResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TrackUserActionResponseValidationError{}

// Validate checks the field values on TrackUserActionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *TrackUserActionRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TrackUserActionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TrackUserActionRequestMultiError, or nil if none found.
func (m *TrackUserActionRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *TrackUserActionRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	// no validation rules for ContentId

	// no validation rules for Action

	if m.Rating != nil {
		// no validation rules for Rating
	}

	if m.DurationSec != nil {
		// no validation rules for DurationSec
	}

	if len(errors) > 0 {
		return TrackUserActionRequestMultiError(errors)
	}

	return nil
}

// TrackUserActionRequestMultiError is an error wrapping multiple validation
// errors returned by TrackUserActionRequest.ValidateAll() if the designated
// constraints aren't met.
type TrackUserActionRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TrackUserActionRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TrackUserActionRequestMultiError) AllErrors() []error { return m }

// TrackUserActionRequestValidationError is the validation error returned by
// TrackUserActionRequest.Validate if the designated constraints aren't met.
type TrackUserActionRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TrackUserActionRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TrackUserActionRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TrackUserActionRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TrackUserActionRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TrackUserActionRequestValidationError) ErrorName() string {
	return "TrackUserActionRequestValidationError"
}

// Error satisfies the builtin error interface
func (e TrackUserActionRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTrackUserActionRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TrackUserActionRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TrackUserActionRequestValidationError{}

// Validate checks the field values on GetSimilarContentRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetSimilarContentRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetSimilarContentRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetSimilarContentRequestMultiError, or nil if none found.
func (m *GetSimilarContentRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetSimilarContentRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ContentId

	// no validation rules for Limit

	if len(errors) > 0 {
		return GetSimilarContentRequestMultiError(errors)
	}

	return nil
}

// GetSimilarContentRequestMultiError is an error wrapping multiple validation
// errors returned by GetSimilarContentRequest.ValidateAll() if the designated
// constraints aren't met.
type GetSimilarContentRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetSimilarContentRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetSimilarContentRequestMultiError) AllErrors() []error { return m }

// GetSimilarContentRequestValidationError is the validation error returned by
// GetSimilarContentRequest.Validate if the designated constraints aren't met.
type GetSimilarContentRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetSimilarContentRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetSimilarContentRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetSimilarContentRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetSimilarContentRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetSimilarContentRequestValidationError) ErrorName() string {
	return "GetSimilarContentRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetSimilarContentRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetSimilarContentRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetSimilarContentRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetSimilarContentRequestValidationError{}

// Validate checks the field values on GetSimilarContentResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetSimilarContentResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetSimilarContentResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetSimilarContentResponseMultiError, or nil if none found.
func (m *GetSimilarContentResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetSimilarContentResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetSimilarContentResponseMultiError(errors)
	}

	return nil
}

// GetSimilarContentResponseMultiError is an error wrapping multiple validation
// errors returned by GetSimilarContentResponse.ValidateAll() if the
// designated constraints aren't met.
type GetSimilarContentResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetSimilarContentResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetSimilarContentResponseMultiError) AllErrors() []error { return m }

// GetSimilarContentResponseValidationError is the validation error returned by
// GetSimilarContentResponse.Validate if the designated constraints aren't met.
type GetSimilarContentResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetSimilarContentResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetSimilarContentResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetSimilarContentResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetSimilarContentResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetSimilarContentResponseValidationError) ErrorName() string {
	return "GetSimilarContentResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetSimilarContentResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetSimilarContentResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetSimilarContentResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetSimilarContentResponseValidationError{}

// Validate checks the field values on GetTrendingContentRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetTrendingContentRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetTrendingContentRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetTrendingContentRequestMultiError, or nil if none found.
func (m *GetTrendingContentRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetTrendingContentRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Limit

	if len(errors) > 0 {
		return GetTrendingContentRequestMultiError(errors)
	}

	return nil
}

// GetTrendingContentRequestMultiError is an error wrapping multiple validation
// errors returned by GetTrendingContentRequest.ValidateAll() if the
// designated constraints aren't met.
type GetTrendingContentRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetTrendingContentRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetTrendingContentRequestMultiError) AllErrors() []error { return m }

// GetTrendingContentRequestValidationError is the validation error returned by
// GetTrendingContentRequest.Validate if the designated constraints aren't met.
type GetTrendingContentRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetTrendingContentRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetTrendingContentRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetTrendingContentRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetTrendingContentRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetTrendingContentRequestValidationError) ErrorName() string {
	return "GetTrendingContentRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetTrendingContentRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetTrendingContentRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetTrendingContentRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetTrendingContentRequestValidationError{}

// Validate checks the field values on GetTrendingContentResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetTrendingContentResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetTrendingContentResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetTrendingContentResponseMultiError, or nil if none found.
func (m *GetTrendingContentResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetTrendingContentResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetTrendingContentResponseMultiError(errors)
	}

	return nil
}

// GetTrendingContentResponseMultiError is an error wrapping multiple
// validation errors returned by GetTrendingContentResponse.ValidateAll() if
// the designated constraints aren't met.
type GetTrendingContentResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetTrendingContentResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetTrendingContentResponseMultiError) AllErrors() []error { return m }

// GetTrendingContentResponseValidationError is the validation error returned
// by GetTrendingContentResponse.Validate if the designated constraints aren't met.
type GetTrendingContentResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetTrendingContentResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetTrendingContentResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetTrendingContentResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetTrendingContentResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetTrendingContentResponseValidationError) ErrorName() string {
	return "GetTrendingContentResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetTrendingContentResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetTrendingContentResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetTrendingContentResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetTrendingContentResponseValidationError{}

// Validate checks the field values on GetUserPreferencesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetUserPreferencesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetUserPreferencesRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetUserPreferencesRequestMultiError, or nil if none found.
func (m *GetUserPreferencesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetUserPreferencesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	if len(errors) > 0 {
		return GetUserPreferencesRequestMultiError(errors)
	}

	return nil
}

// GetUserPreferencesRequestMultiError is an error wrapping multiple validation
// errors returned by GetUserPreferencesRequest.ValidateAll() if the
// designated constraints aren't met.
type GetUserPreferencesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUserPreferencesRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetUserPreferencesRequestMultiError) AllErrors() []error { return m }

// GetUserPreferencesRequestValidationError is the validation error returned by
// GetUserPreferencesRequest.Validate if the designated constraints aren't met.
type GetUserPreferencesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserPreferencesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUserPreferencesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUserPreferencesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUserPreferencesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUserPreferencesRequestValidationError) ErrorName() string {
	return "GetUserPreferencesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetUserPreferencesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUserPreferencesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUserPreferencesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserPreferencesRequestValidationError{}

// Validate checks the field values on GetUserPreferencesResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetUserPreferencesResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetUserPreferencesResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetUserPreferencesResponseMultiError, or nil if none found.
func (m *GetUserPreferencesResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetUserPreferencesResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetUserPreferencesResponseMultiError(errors)
	}

	return nil
}

// GetUserPreferencesResponseMultiError is an error wrapping multiple
// validation errors returned by GetUserPreferencesResponse.ValidateAll() if
// the designated constraints aren't met.
type GetUserPreferencesResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUserPreferencesResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetUserPreferencesResponseMultiError) AllErrors() []error { return m }

// GetUserPreferencesResponseValidationError is the validation error returned
// by GetUserPreferencesResponse.Validate if the designated constraints aren't met.
type GetUserPreferencesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserPreferencesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUserPreferencesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUserPreferencesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUserPreferencesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUserPreferencesResponseValidationError) ErrorName() string {
	return "GetUserPreferencesResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetUserPreferencesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUserPreferencesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUserPreferencesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserPreferencesResponseValidationError{}

// Validate checks the field values on SetUserPreferencesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SetUserPreferencesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SetUserPreferencesRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SetUserPreferencesRequestMultiError, or nil if none found.
func (m *SetUserPreferencesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SetUserPreferencesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	if len(errors) > 0 {
		return SetUserPreferencesRequestMultiError(errors)
	}

	return nil
}

// SetUserPreferencesRequestMultiError is an error wrapping multiple validation
// errors returned by SetUserPreferencesRequest.ValidateAll() if the
// designated constraints aren't met.
type SetUserPreferencesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SetUserPreferencesRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SetUserPreferencesRequestMultiError) AllErrors() []error { return m }

// SetUserPreferencesRequestValidationError is the validation error returned by
// SetUserPreferencesRequest.Validate if the designated constraints aren't met.
type SetUserPreferencesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SetUserPreferencesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SetUserPreferencesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SetUserPreferencesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SetUserPreferencesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SetUserPreferencesRequestValidationError) ErrorName() string {
	return "SetUserPreferencesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SetUserPreferencesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSetUserPreferencesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SetUserPreferencesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SetUserPreferencesRequestValidationError{}

// Validate checks the field values on SetUserPreferencesResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SetUserPreferencesResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SetUserPreferencesResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SetUserPreferencesResponseMultiError, or nil if none found.
func (m *SetUserPreferencesResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *SetUserPreferencesResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserPreferencesSetted

	if len(errors) > 0 {
		return SetUserPreferencesResponseMultiError(errors)
	}

	return nil
}

// SetUserPreferencesResponseMultiError is an error wrapping multiple
// validation errors returned by SetUserPreferencesResponse.ValidateAll() if
// the designated constraints aren't met.
type SetUserPreferencesResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SetUserPreferencesResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SetUserPreferencesResponseMultiError) AllErrors() []error { return m }

// SetUserPreferencesResponseValidationError is the validation error returned
// by SetUserPreferencesResponse.Validate if the designated constraints aren't met.
type SetUserPreferencesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SetUserPreferencesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SetUserPreferencesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SetUserPreferencesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SetUserPreferencesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SetUserPreferencesResponseValidationError) ErrorName() string {
	return "SetUserPreferencesResponseValidationError"
}

// Error satisfies the builtin error interface
func (e SetUserPreferencesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSetUserPreferencesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SetUserPreferencesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SetUserPreferencesResponseValidationError{}

// Validate checks the field values on ResetUserPreferencesRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ResetUserPreferencesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ResetUserPreferencesRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ResetUserPreferencesRequestMultiError, or nil if none found.
func (m *ResetUserPreferencesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ResetUserPreferencesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	if len(errors) > 0 {
		return ResetUserPreferencesRequestMultiError(errors)
	}

	return nil
}

// ResetUserPreferencesRequestMultiError is an error wrapping multiple
// validation errors returned by ResetUserPreferencesRequest.ValidateAll() if
// the designated constraints aren't met.
type ResetUserPreferencesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ResetUserPreferencesRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ResetUserPreferencesRequestMultiError) AllErrors() []error { return m }

// ResetUserPreferencesRequestValidationError is the validation error returned
// by ResetUserPreferencesRequest.Validate if the designated constraints
// aren't met.
type ResetUserPreferencesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ResetUserPreferencesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ResetUserPreferencesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ResetUserPreferencesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ResetUserPreferencesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ResetUserPreferencesRequestValidationError) ErrorName() string {
	return "ResetUserPreferencesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ResetUserPreferencesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sResetUserPreferencesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ResetUserPreferencesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ResetUserPreferencesRequestValidationError{}

// Validate checks the field values on ResetUserPreferencesResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ResetUserPreferencesResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ResetUserPreferencesResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ResetUserPreferencesResponseMultiError, or nil if none found.
func (m *ResetUserPreferencesResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ResetUserPreferencesResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserPreferencesResetted

	if len(errors) > 0 {
		return ResetUserPreferencesResponseMultiError(errors)
	}

	return nil
}

// ResetUserPreferencesResponseMultiError is an error wrapping multiple
// validation errors returned by ResetUserPreferencesResponse.ValidateAll() if
// the designated constraints aren't met.
type ResetUserPreferencesResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ResetUserPreferencesResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ResetUserPreferencesResponseMultiError) AllErrors() []error { return m }

// ResetUserPreferencesResponseValidationError is the validation error returned
// by ResetUserPreferencesResponse.Validate if the designated constraints
// aren't met.
type ResetUserPreferencesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ResetUserPreferencesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ResetUserPreferencesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ResetUserPreferencesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ResetUserPreferencesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ResetUserPreferencesResponseValidationError) ErrorName() string {
	return "ResetUserPreferencesResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ResetUserPreferencesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sResetUserPreferencesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ResetUserPreferencesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ResetUserPreferencesResponseValidationError{}

// Validate checks the field values on RebuildUserPreferencesRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RebuildUserPreferencesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RebuildUserPreferencesRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// RebuildUserPreferencesRequestMultiError, or nil if none found.
func (m *RebuildUserPreferencesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *RebuildUserPreferencesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	if len(errors) > 0 {
		return RebuildUserPreferencesRequestMultiError(errors)
	}

	return nil
}

// RebuildUserPreferencesRequestMultiError is an error wrapping multiple
// validation errors returned by RebuildUserPreferencesRequest.ValidateAll()
// if the designated constraints aren't met.
type RebuildUserPreferencesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RebuildUserPreferencesRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RebuildUserPreferencesRequestMultiError) AllErrors() []error { return m }

// RebuildUserPreferencesRequestValidationError is the validation error
// returned by RebuildUserPreferencesRequest.Validate if the designated
// constraints aren't met.
type RebuildUserPreferencesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RebuildUserPreferencesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RebuildUserPreferencesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RebuildUserPreferencesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RebuildUserPreferencesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RebuildUserPreferencesRequestValidationError) ErrorName() string {
	return "RebuildUserPreferencesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e RebuildUserPreferencesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRebuildUserPreferencesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RebuildUserPreferencesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RebuildUserPreferencesRequestValidationError{}

// Validate checks the field values on RebuildUserPreferencesResponce with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RebuildUserPreferencesResponce) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RebuildUserPreferencesResponce with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// RebuildUserPreferencesResponceMultiError, or nil if none found.
func (m *RebuildUserPreferencesResponce) ValidateAll() error {
	return m.validate(true)
}

func (m *RebuildUserPreferencesResponce) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return RebuildUserPreferencesResponceMultiError(errors)
	}

	return nil
}

// RebuildUserPreferencesResponceMultiError is an error wrapping multiple
// validation errors returned by RebuildUserPreferencesResponce.ValidateAll()
// if the designated constraints aren't met.
type RebuildUserPreferencesResponceMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RebuildUserPreferencesResponceMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RebuildUserPreferencesResponceMultiError) AllErrors() []error { return m }

// RebuildUserPreferencesResponceValidationError is the validation error
// returned by RebuildUserPreferencesResponce.Validate if the designated
// constraints aren't met.
type RebuildUserPreferencesResponceValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RebuildUserPreferencesResponceValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RebuildUserPreferencesResponceValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RebuildUserPreferencesResponceValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RebuildUserPreferencesResponceValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RebuildUserPreferencesResponceValidationError) ErrorName() string {
	return "RebuildUserPreferencesResponceValidationError"
}

// Error satisfies the builtin error interface
func (e RebuildUserPreferencesResponceValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRebuildUserPreferencesResponce.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RebuildUserPreferencesResponceValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RebuildUserPreferencesResponceValidationError{}

// Validate checks the field values on GetPopularContentRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetPopularContentRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetPopularContentRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetPopularContentRequestMultiError, or nil if none found.
func (m *GetPopularContentRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetPopularContentRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Limit

	if len(errors) > 0 {
		return GetPopularContentRequestMultiError(errors)
	}

	return nil
}

// GetPopularContentRequestMultiError is an error wrapping multiple validation
// errors returned by GetPopularContentRequest.ValidateAll() if the designated
// constraints aren't met.
type GetPopularContentRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetPopularContentRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetPopularContentRequestMultiError) AllErrors() []error { return m }

// GetPopularContentRequestValidationError is the validation error returned by
// GetPopularContentRequest.Validate if the designated constraints aren't met.
type GetPopularContentRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetPopularContentRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetPopularContentRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetPopularContentRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetPopularContentRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetPopularContentRequestValidationError) ErrorName() string {
	return "GetPopularContentRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetPopularContentRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetPopularContentRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetPopularContentRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetPopularContentRequestValidationError{}

// Validate checks the field values on GetPopularContentResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetPopularContentResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetPopularContentResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetPopularContentResponseMultiError, or nil if none found.
func (m *GetPopularContentResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetPopularContentResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetPopularContentResponseMultiError(errors)
	}

	return nil
}

// GetPopularContentResponseMultiError is an error wrapping multiple validation
// errors returned by GetPopularContentResponse.ValidateAll() if the
// designated constraints aren't met.
type GetPopularContentResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetPopularContentResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetPopularContentResponseMultiError) AllErrors() []error { return m }

// GetPopularContentResponseValidationError is the validation error returned by
// GetPopularContentResponse.Validate if the designated constraints aren't met.
type GetPopularContentResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetPopularContentResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetPopularContentResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetPopularContentResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetPopularContentResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetPopularContentResponseValidationError) ErrorName() string {
	return "GetPopularContentResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetPopularContentResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetPopularContentResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetPopularContentResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetPopularContentResponseValidationError{}
