// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: rec-system/rec.proto

package recommendationpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RecommendationService_GetRecommendations_FullMethodName         = "/recommendation.RecommendationService/GetRecommendations"
	RecommendationService_TrackUserAction_FullMethodName            = "/recommendation.RecommendationService/TrackUserAction"
	RecommendationService_GetAIRecommendations_FullMethodName       = "/recommendation.RecommendationService/GetAIRecommendations"
	RecommendationService_GetRecommendationsByGenres_FullMethodName = "/recommendation.RecommendationService/GetRecommendationsByGenres"
	RecommendationService_GetSimilarContent_FullMethodName          = "/recommendation.RecommendationService/GetSimilarContent"
	RecommendationService_GetTrendingContent_FullMethodName         = "/recommendation.RecommendationService/GetTrendingContent"
	RecommendationService_GetUserPreferences_FullMethodName         = "/recommendation.RecommendationService/GetUserPreferences"
	RecommendationService_SetUserPreferences_FullMethodName         = "/recommendation.RecommendationService/SetUserPreferences"
	RecommendationService_ResetUserPreferences_FullMethodName       = "/recommendation.RecommendationService/ResetUserPreferences"
	RecommendationService_RebuildUserPreferences_FullMethodName     = "/recommendation.RecommendationService/RebuildUserPreferences"
	RecommendationService_GetPopularContent_FullMethodName          = "/recommendation.RecommendationService/GetPopularContent"
)

// RecommendationServiceClient is the client API for RecommendationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RecommendationServiceClient interface {
	//core
	GetRecommendations(ctx context.Context, in *GetRecommendationsRequest, opts ...grpc.CallOption) (*GetRecommendationsResponse, error)
	TrackUserAction(ctx context.Context, in *TrackUserActionRequest, opts ...grpc.CallOption) (*TrackUserActionResponse, error)
	GetAIRecommendations(ctx context.Context, in *GetAIRecommendationsRequest, opts ...grpc.CallOption) (*GetAIRecommendationsResponse, error)
	GetRecommendationsByGenres(ctx context.Context, in *GetRecommendationsByGenresRequest, opts ...grpc.CallOption) (*GetRecommendationsByGenresResponse, error)
	GetSimilarContent(ctx context.Context, in *GetSimilarContentRequest, opts ...grpc.CallOption) (*GetSimilarContentResponse, error)
	GetTrendingContent(ctx context.Context, in *GetTrendingContentRequest, opts ...grpc.CallOption) (*GetTrendingContentResponse, error)
	// preferences
	GetUserPreferences(ctx context.Context, in *GetUserPreferencesRequest, opts ...grpc.CallOption) (*GetUserPreferencesResponse, error)
	SetUserPreferences(ctx context.Context, in *SetUserPreferencesRequest, opts ...grpc.CallOption) (*SetUserPreferencesResponse, error)
	ResetUserPreferences(ctx context.Context, in *ResetUserPreferencesRequest, opts ...grpc.CallOption) (*ResetUserPreferencesResponse, error)
	RebuildUserPreferences(ctx context.Context, in *RebuildUserPreferencesRequest, opts ...grpc.CallOption) (*RebuildUserPreferencesResponce, error)
	// cold start
	GetPopularContent(ctx context.Context, in *GetPopularContentRequest, opts ...grpc.CallOption) (*GetPopularContentResponse, error)
}

type recommendationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRecommendationServiceClient(cc grpc.ClientConnInterface) RecommendationServiceClient {
	return &recommendationServiceClient{cc}
}

func (c *recommendationServiceClient) GetRecommendations(ctx context.Context, in *GetRecommendationsRequest, opts ...grpc.CallOption) (*GetRecommendationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRecommendationsResponse)
	err := c.cc.Invoke(ctx, RecommendationService_GetRecommendations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recommendationServiceClient) TrackUserAction(ctx context.Context, in *TrackUserActionRequest, opts ...grpc.CallOption) (*TrackUserActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrackUserActionResponse)
	err := c.cc.Invoke(ctx, RecommendationService_TrackUserAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recommendationServiceClient) GetAIRecommendations(ctx context.Context, in *GetAIRecommendationsRequest, opts ...grpc.CallOption) (*GetAIRecommendationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAIRecommendationsResponse)
	err := c.cc.Invoke(ctx, RecommendationService_GetAIRecommendations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recommendationServiceClient) GetRecommendationsByGenres(ctx context.Context, in *GetRecommendationsByGenresRequest, opts ...grpc.CallOption) (*GetRecommendationsByGenresResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRecommendationsByGenresResponse)
	err := c.cc.Invoke(ctx, RecommendationService_GetRecommendationsByGenres_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recommendationServiceClient) GetSimilarContent(ctx context.Context, in *GetSimilarContentRequest, opts ...grpc.CallOption) (*GetSimilarContentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSimilarContentResponse)
	err := c.cc.Invoke(ctx, RecommendationService_GetSimilarContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recommendationServiceClient) GetTrendingContent(ctx context.Context, in *GetTrendingContentRequest, opts ...grpc.CallOption) (*GetTrendingContentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTrendingContentResponse)
	err := c.cc.Invoke(ctx, RecommendationService_GetTrendingContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recommendationServiceClient) GetUserPreferences(ctx context.Context, in *GetUserPreferencesRequest, opts ...grpc.CallOption) (*GetUserPreferencesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserPreferencesResponse)
	err := c.cc.Invoke(ctx, RecommendationService_GetUserPreferences_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recommendationServiceClient) SetUserPreferences(ctx context.Context, in *SetUserPreferencesRequest, opts ...grpc.CallOption) (*SetUserPreferencesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetUserPreferencesResponse)
	err := c.cc.Invoke(ctx, RecommendationService_SetUserPreferences_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recommendationServiceClient) ResetUserPreferences(ctx context.Context, in *ResetUserPreferencesRequest, opts ...grpc.CallOption) (*ResetUserPreferencesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetUserPreferencesResponse)
	err := c.cc.Invoke(ctx, RecommendationService_ResetUserPreferences_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recommendationServiceClient) RebuildUserPreferences(ctx context.Context, in *RebuildUserPreferencesRequest, opts ...grpc.CallOption) (*RebuildUserPreferencesResponce, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RebuildUserPreferencesResponce)
	err := c.cc.Invoke(ctx, RecommendationService_RebuildUserPreferences_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recommendationServiceClient) GetPopularContent(ctx context.Context, in *GetPopularContentRequest, opts ...grpc.CallOption) (*GetPopularContentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPopularContentResponse)
	err := c.cc.Invoke(ctx, RecommendationService_GetPopularContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecommendationServiceServer is the server API for RecommendationService service.
// All implementations must embed UnimplementedRecommendationServiceServer
// for forward compatibility.
type RecommendationServiceServer interface {
	//core
	GetRecommendations(context.Context, *GetRecommendationsRequest) (*GetRecommendationsResponse, error)
	TrackUserAction(context.Context, *TrackUserActionRequest) (*TrackUserActionResponse, error)
	GetAIRecommendations(context.Context, *GetAIRecommendationsRequest) (*GetAIRecommendationsResponse, error)
	GetRecommendationsByGenres(context.Context, *GetRecommendationsByGenresRequest) (*GetRecommendationsByGenresResponse, error)
	GetSimilarContent(context.Context, *GetSimilarContentRequest) (*GetSimilarContentResponse, error)
	GetTrendingContent(context.Context, *GetTrendingContentRequest) (*GetTrendingContentResponse, error)
	// preferences
	GetUserPreferences(context.Context, *GetUserPreferencesRequest) (*GetUserPreferencesResponse, error)
	SetUserPreferences(context.Context, *SetUserPreferencesRequest) (*SetUserPreferencesResponse, error)
	ResetUserPreferences(context.Context, *ResetUserPreferencesRequest) (*ResetUserPreferencesResponse, error)
	RebuildUserPreferences(context.Context, *RebuildUserPreferencesRequest) (*RebuildUserPreferencesResponce, error)
	// cold start
	GetPopularContent(context.Context, *GetPopularContentRequest) (*GetPopularContentResponse, error)
	mustEmbedUnimplementedRecommendationServiceServer()
}

// UnimplementedRecommendationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRecommendationServiceServer struct{}

func (UnimplementedRecommendationServiceServer) GetRecommendations(context.Context, *GetRecommendationsRequest) (*GetRecommendationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecommendations not implemented")
}
func (UnimplementedRecommendationServiceServer) TrackUserAction(context.Context, *TrackUserActionRequest) (*TrackUserActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TrackUserAction not implemented")
}
func (UnimplementedRecommendationServiceServer) GetAIRecommendations(context.Context, *GetAIRecommendationsRequest) (*GetAIRecommendationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAIRecommendations not implemented")
}
func (UnimplementedRecommendationServiceServer) GetRecommendationsByGenres(context.Context, *GetRecommendationsByGenresRequest) (*GetRecommendationsByGenresResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecommendationsByGenres not implemented")
}
func (UnimplementedRecommendationServiceServer) GetSimilarContent(context.Context, *GetSimilarContentRequest) (*GetSimilarContentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSimilarContent not implemented")
}
func (UnimplementedRecommendationServiceServer) GetTrendingContent(context.Context, *GetTrendingContentRequest) (*GetTrendingContentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrendingContent not implemented")
}
func (UnimplementedRecommendationServiceServer) GetUserPreferences(context.Context, *GetUserPreferencesRequest) (*GetUserPreferencesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserPreferences not implemented")
}
func (UnimplementedRecommendationServiceServer) SetUserPreferences(context.Context, *SetUserPreferencesRequest) (*SetUserPreferencesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetUserPreferences not implemented")
}
func (UnimplementedRecommendationServiceServer) ResetUserPreferences(context.Context, *ResetUserPreferencesRequest) (*ResetUserPreferencesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetUserPreferences not implemented")
}
func (UnimplementedRecommendationServiceServer) RebuildUserPreferences(context.Context, *RebuildUserPreferencesRequest) (*RebuildUserPreferencesResponce, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RebuildUserPreferences not implemented")
}
func (UnimplementedRecommendationServiceServer) GetPopularContent(context.Context, *GetPopularContentRequest) (*GetPopularContentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPopularContent not implemented")
}
func (UnimplementedRecommendationServiceServer) mustEmbedUnimplementedRecommendationServiceServer() {}
func (UnimplementedRecommendationServiceServer) testEmbeddedByValue()                               {}

// UnsafeRecommendationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecommendationServiceServer will
// result in compilation errors.
type UnsafeRecommendationServiceServer interface {
	mustEmbedUnimplementedRecommendationServiceServer()
}

func RegisterRecommendationServiceServer(s grpc.ServiceRegistrar, srv RecommendationServiceServer) {
	// If the following call pancis, it indicates UnimplementedRecommendationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RecommendationService_ServiceDesc, srv)
}

func _RecommendationService_GetRecommendations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecommendationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendationServiceServer).GetRecommendations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecommendationService_GetRecommendations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendationServiceServer).GetRecommendations(ctx, req.(*GetRecommendationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecommendationService_TrackUserAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrackUserActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendationServiceServer).TrackUserAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecommendationService_TrackUserAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendationServiceServer).TrackUserAction(ctx, req.(*TrackUserActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecommendationService_GetAIRecommendations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAIRecommendationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendationServiceServer).GetAIRecommendations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecommendationService_GetAIRecommendations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendationServiceServer).GetAIRecommendations(ctx, req.(*GetAIRecommendationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecommendationService_GetRecommendationsByGenres_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecommendationsByGenresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendationServiceServer).GetRecommendationsByGenres(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecommendationService_GetRecommendationsByGenres_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendationServiceServer).GetRecommendationsByGenres(ctx, req.(*GetRecommendationsByGenresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecommendationService_GetSimilarContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSimilarContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendationServiceServer).GetSimilarContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecommendationService_GetSimilarContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendationServiceServer).GetSimilarContent(ctx, req.(*GetSimilarContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecommendationService_GetTrendingContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrendingContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendationServiceServer).GetTrendingContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecommendationService_GetTrendingContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendationServiceServer).GetTrendingContent(ctx, req.(*GetTrendingContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecommendationService_GetUserPreferences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserPreferencesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendationServiceServer).GetUserPreferences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecommendationService_GetUserPreferences_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendationServiceServer).GetUserPreferences(ctx, req.(*GetUserPreferencesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecommendationService_SetUserPreferences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUserPreferencesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendationServiceServer).SetUserPreferences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecommendationService_SetUserPreferences_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendationServiceServer).SetUserPreferences(ctx, req.(*SetUserPreferencesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecommendationService_ResetUserPreferences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetUserPreferencesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendationServiceServer).ResetUserPreferences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecommendationService_ResetUserPreferences_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendationServiceServer).ResetUserPreferences(ctx, req.(*ResetUserPreferencesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecommendationService_RebuildUserPreferences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RebuildUserPreferencesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendationServiceServer).RebuildUserPreferences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecommendationService_RebuildUserPreferences_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendationServiceServer).RebuildUserPreferences(ctx, req.(*RebuildUserPreferencesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecommendationService_GetPopularContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPopularContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendationServiceServer).GetPopularContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecommendationService_GetPopularContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendationServiceServer).GetPopularContent(ctx, req.(*GetPopularContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RecommendationService_ServiceDesc is the grpc.ServiceDesc for RecommendationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RecommendationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "recommendation.RecommendationService",
	HandlerType: (*RecommendationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRecommendations",
			Handler:    _RecommendationService_GetRecommendations_Handler,
		},
		{
			MethodName: "TrackUserAction",
			Handler:    _RecommendationService_TrackUserAction_Handler,
		},
		{
			MethodName: "GetAIRecommendations",
			Handler:    _RecommendationService_GetAIRecommendations_Handler,
		},
		{
			MethodName: "GetRecommendationsByGenres",
			Handler:    _RecommendationService_GetRecommendationsByGenres_Handler,
		},
		{
			MethodName: "GetSimilarContent",
			Handler:    _RecommendationService_GetSimilarContent_Handler,
		},
		{
			MethodName: "GetTrendingContent",
			Handler:    _RecommendationService_GetTrendingContent_Handler,
		},
		{
			MethodName: "GetUserPreferences",
			Handler:    _RecommendationService_GetUserPreferences_Handler,
		},
		{
			MethodName: "SetUserPreferences",
			Handler:    _RecommendationService_SetUserPreferences_Handler,
		},
		{
			MethodName: "ResetUserPreferences",
			Handler:    _RecommendationService_ResetUserPreferences_Handler,
		},
		{
			MethodName: "RebuildUserPreferences",
			Handler:    _RecommendationService_RebuildUserPreferences_Handler,
		},
		{
			MethodName: "GetPopularContent",
			Handler:    _RecommendationService_GetPopularContent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rec-system/rec.proto",
}
