syntax = "proto3";

package catalog;

option go_package = "catalog-system-microservice/internal/pb/catalog;catalogpb";

service CatalogService {

  rpc CreateContent(CreateContentRequest) returns (CreateContentResponse);
  rpc GetContent(GetContentRequest) returns (GetContentResponse);
  rpc UpdateContent(UpdateContentRequest) returns (UpdateContentResponse);

  rpc FindContentByExternal(FindContentByExternalRequest)
      returns (FindContentByExternalResponse);

  rpc GetMovieDetails(GetMovieDetailsRequest) returns (GetMovieDetailsResponse);
  rpc GetAnimeDetails(GetAnimeDetailsRequest) returns (GetAnimeDetailsResponse);
  rpc GetGameDetails(GetGameDetailsRequest) returns (GetGameDetailsResponse);
  rpc GetSeriesDetails(GetSeriesDetailsRequest) returns (GetSeriesDetailsResponse);
  rpc GetBookDetails(GetBookDetailsRequest) returns (GetBookDetailsResponse);
}

// Type of content
enum ContentType {
  CONTENT_TYPE_UNSPECIFIED = 0;
  MOVIE = 1;
  SERIES = 2;
  ANIME = 3;
  GAME = 4;
  BOOK = 5;
}

// Basic model of content
message Content {
  string id = 1;                 // UUID
  ContentType type = 2;          // movie, anime, game, series, book
  string external_source = 3;    // tmdb, igdb, anilist, openlibrary, googlebooks
  string external_id = 4;        // ID from outer API
  string title = 5;
  string description = 6;
  string poster_url = 7;
  string release_date = 8;       // ISO8601
  string created_at = 9;
  string updated_at = 10;
}

// ----------------------
// Detail data
// ----------------------

// Movies (movies_details)
message MovieDetails {
  string content_id = 1;
  int32 tmdb_id = 2;
  int32 runtime = 3;
  string tagline = 4;
  string status = 5;
  int64 budget = 6;
  int64 revenue = 7;
  string language = 8;

  string genres_json = 9;
  string cast_json = 10;
  string crew_json = 11;
  string images_json = 12;
  string videos_json = 13;
  string raw_json = 14;
}

// Anime (anime_details)
message AnimeDetails {
  string content_id = 1;
  int32 anilist_id = 2;
  int32 mal_id = 3;
  int32 episodes_count = 4;
  string status = 5;
  string season = 6;

  string studios_json = 7;
  string genres_json = 8;
  string trailer_url = 9;
  string raw_json = 10;
}

// Games (games_details)
message GameDetails {
  string content_id = 1;
  int32 igdb_id = 2;
  string platforms_json = 3;
  string screenshots_json = 4;
  double rating = 5;
  string genres_json = 6;
  string developers_json = 7;
  string publishers_json = 8;
  string raw_json = 9;
}

// Series (series_details)
message SeriesDetails {
  string content_id = 1;
  int32 tmdb_id = 2;
  string seasons_json = 3;
  string episodes_json = 4;
  string networks_json = 5;
  string genres_json = 6;
  string cast_json = 7;
  string images_json = 8;
  string raw_json = 9;
}

// ----------------------
// BOOKS (books_details)
// ----------------------

message BookDetails {
  string content_id = 1;

  string isbn_10 = 2;
  string isbn_13 = 3;
  string language = 4;
  int32 pages = 5;

  string authors_json = 6;
  string publishers_json = 7;
  string genres_json = 8;

  string raw_json = 9; // full JSON from OpenLibrary / Google Books
}



message GetContentRequest {
  string id = 1;
}

message GetContentResponse {
  Content content = 1;
}

message FindContentByExternalRequest {
  string external_source = 1;
  string external_id = 2;
}

message FindContentByExternalResponse {
  Content content = 1;
}

// Create New Content
message CreateContentRequest {
  Content content = 1;
}

message CreateContentResponse {
  Content content = 1;
}

// Обновление метаданных контента
message UpdateContentRequest {
  Content content = 1;
}

message UpdateContentResponse {
  Content content = 1;
}


//MOVIE

message GetMovieDetailsRequest {
  string content_id = 1;
}

message GetMovieDetailsResponse {
  MovieDetails details = 1;
}

//ANIME

message GetAnimeDetailsRequest {
  string content_id = 1;
}

message GetAnimeDetailsResponse {
  AnimeDetails details = 1;
}

//GAMES

message GetGameDetailsRequest {
  string content_id = 1;
}

message GetGameDetailsResponse {
  GameDetails details = 1;
}

//SERIES

message GetSeriesDetailsRequest {
  string content_id = 1;
}

message GetSeriesDetailsResponse {
  SeriesDetails details = 1;
}

// BOOKS

message GetBookDetailsRequest {
  string content_id = 1;
}

message GetBookDetailsResponse {
  BookDetails details = 1;
}
