syntax = "proto3";

package catalog;

option go_package = "catalog-system-microservice/internal/pb/catalog;catalogpb";

service CatalogService {

  rpc CreateContent(CreateContentRequest) returns (CreateContentResponse);
  rpc GetContent(GetContentRequest) returns (GetContentResponse);
  rpc UpdateContent(UpdateContentRequest) returns (UpdateContentResponse);

  rpc FindContentByExternal(FindContentByExternalRequest)
      returns (FindContentByExternalResponse);

  rpc GetMovieDetails(GetMovieDetailsRequest) returns (GetMovieDetailsResponse);
  rpc GetAnimeDetails(GetAnimeDetailsRequest) returns (GetAnimeDetailsResponse);
  rpc GetGameDetails(GetGameDetailsRequest) returns (GetGameDetailsResponse);
  rpc GetSeriesDetails(GetSeriesDetailsRequest) returns (GetSeriesDetailsResponse);
  rpc GetBookDetails(GetBookDetailsRequest) returns (GetBookDetailsResponse);

  rpc GetAllMovieDetails(GetAllMovieDetailsRequest) returns (GetAllMovieDetailsResponse);
  rpc GetAllAnimeDetails(GetAllAnimeDetailsRequest) returns (GetAllAnimeDetailsResponse);
  rpc GetAllGameDetails(GetAllGameDetailsRequest) returns (GetAllGameDetailsResponse);
  rpc GetAllSeriesDetails(GetAllSeriesDetailsRequest) returns (GetAllSeriesDetailsResponse);
  rpc GetAllBookDetails(GetAllBookDetailsRequest) returns (GetAllBookDetailsResponse);
}

// ----------------------
// Content
// ----------------------

enum ContentType {
  CONTENT_TYPE_UNSPECIFIED = 0;
  MOVIE = 1;
  SERIES = 2;
  ANIME = 3;
  GAME = 4;
  BOOK = 5;
}

message Content {
  string id = 1;                 // UUID
  ContentType type = 2;
  string external_source = 3;    // tmdb | igdb | anilist | openlibrary | googlebooks
  string external_id = 4;

  string title = 5;
  string description = 6;
  string poster_url = 7;
  string release_date = 8;       // YYYY-MM-DD

  string created_at = 9;
  string updated_at = 10;
}

// ----------------------
// Movies
// ----------------------

message MovieDetails {
  string content_id = 1;
  int32 tmdb_id = 2;

  string original_title = 3;
  int32 runtime = 4;
  string tagline = 5;
  string status = 6;

  int64 budget = 7;
  int64 revenue = 8;
  string language = 9;

  string genres_json = 10;
  string cast_json = 11;
  string crew_json = 12;
  string images_json = 13;
  string videos_json = 14;

  string raw_json = 15;
}

// ----------------------
// Series
// ----------------------

message SeriesDetails {
  string content_id = 1;
  int32 tmdb_id = 2;

  string original_name = 3;
  string status = 4;

  string first_air_date = 5;
  string last_air_date = 6;

  int32 number_of_seasons = 7;
  int32 number_of_episodes = 8;

  string language = 9;

  string genres_json = 10;
  string networks_json = 11;
  string cast_json = 12;
  string images_json = 13;
  string videos_json = 14;

  string raw_json = 15;
}

// ----------------------
// Anime
// ----------------------

message AnimeDetails {
  string content_id = 1;

  int32 anilist_id = 2;
  int32 mal_id = 3;

  string original_title = 4;
  string format = 5;          // TV | MOVIE | OVA | ONA
  string status = 6;          // FINISHED | RELEASING
  string season = 7;          // WINTER | SPRING | SUMMER | FALL
  int32 season_year = 8;

  int32 episodes_count = 9;
  int32 episode_duration = 10;

  string start_date = 11;
  string end_date = 12;

  string language = 13;

  string genres_json = 14;
  string tags_json = 15;
  string studios_json = 16;

  string characters_json = 17;
  string voice_actors_json = 18;

  int32 mean_score = 19;
  int32 popularity = 20;
  int32 favourites = 21;

  string trailer_url = 22;

  string raw_json = 23;
}

// ----------------------
// Games
// ----------------------

message GameDetails {
  string content_id = 1;
  int32 igdb_id = 2;

  double rating = 3;

  string genres_json = 4;
  string platforms_json = 5;
  string developers_json = 6;
  string publishers_json = 7;
  string screenshots_json = 8;

  string raw_json = 9;
}

// ----------------------
// Books
// ----------------------

message BookDetails {
  string content_id = 1;

  string isbn_10 = 2;
  string isbn_13 = 3;

  string language = 4;
  int32 pages = 5;

  string publish_date = 6;

  string authors_json = 7;
  string publishers_json = 8;
  string genres_json = 9;

  string raw_json = 10;
}

// ----------------------
// Requests / Responses
// ----------------------

message GetContentRequest {
  string id = 1;
}

message GetContentResponse {
  Content content = 1;
}

message FindContentByExternalRequest {
  string external_source = 1;
  string external_id = 2;
}

message FindContentByExternalResponse {
  Content content = 1;
}

message CreateContentRequest {
  Content content = 1;
}

message CreateContentResponse {
  Content content = 1;
}

message UpdateContentRequest {
  Content content = 1;
}

message UpdateContentResponse {
  Content content = 1;
}

// ---- detail getters ----

message GetMovieDetailsRequest {
  string content_id = 1;
}

message GetMovieDetailsResponse {
  MovieDetails details = 1;
}

message GetAnimeDetailsRequest {
  string content_id = 1;
}

message GetAnimeDetailsResponse {
  AnimeDetails details = 1;
}

message GetGameDetailsRequest {
  string content_id = 1;
}

message GetGameDetailsResponse {
  GameDetails details = 1;
}

message GetSeriesDetailsRequest {
  string content_id = 1;
}

message GetSeriesDetailsResponse {
  SeriesDetails details = 1;
}

message GetBookDetailsRequest {
  string content_id = 1;
}

message GetBookDetailsResponse {
  BookDetails details = 1;
}



// ----getter of all details

message GetAllMovieDetailsRequest {

}

message GetAllMovieDetailsResponse {
  repeated MovieDetails details = 1;
}

message GetAllAnimeDetailsRequest {

}

message GetAllAnimeDetailsResponse {
  repeated AnimeDetails details = 1;
}

message GetAllGameDetailsRequest {

}

message GetAllGameDetailsResponse {
  repeated GameDetails details = 1;
}

message GetAllSeriesDetailsRequest {

}

message GetAllSeriesDetailsResponse {
  repeated SeriesDetails details = 1;
}

message GetAllBookDetailsRequest {

}

message GetAllBookDetailsResponse {
  repeated BookDetails details = 1;
}
