// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: catalog-system/catalog.proto

package catalogpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContentType int32

const (
	ContentType_CONTENT_TYPE_UNSPECIFIED ContentType = 0
	ContentType_MOVIE                    ContentType = 1
	ContentType_SERIES                   ContentType = 2
	ContentType_ANIME                    ContentType = 3
	ContentType_GAME                     ContentType = 4
	ContentType_BOOK                     ContentType = 5
)

// Enum value maps for ContentType.
var (
	ContentType_name = map[int32]string{
		0: "CONTENT_TYPE_UNSPECIFIED",
		1: "MOVIE",
		2: "SERIES",
		3: "ANIME",
		4: "GAME",
		5: "BOOK",
	}
	ContentType_value = map[string]int32{
		"CONTENT_TYPE_UNSPECIFIED": 0,
		"MOVIE":                    1,
		"SERIES":                   2,
		"ANIME":                    3,
		"GAME":                     4,
		"BOOK":                     5,
	}
)

func (x ContentType) Enum() *ContentType {
	p := new(ContentType)
	*p = x
	return p
}

func (x ContentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContentType) Descriptor() protoreflect.EnumDescriptor {
	return file_catalog_system_catalog_proto_enumTypes[0].Descriptor()
}

func (ContentType) Type() protoreflect.EnumType {
	return &file_catalog_system_catalog_proto_enumTypes[0]
}

func (x ContentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContentType.Descriptor instead.
func (ContentType) EnumDescriptor() ([]byte, []int) {
	return file_catalog_system_catalog_proto_rawDescGZIP(), []int{0}
}

type Content struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // UUID
	Type           ContentType            `protobuf:"varint,2,opt,name=type,proto3,enum=catalog.ContentType" json:"type,omitempty"`
	ExternalSource string                 `protobuf:"bytes,3,opt,name=external_source,json=externalSource,proto3" json:"external_source,omitempty"` // tmdb | igdb | anilist | openlibrary | googlebooks
	ExternalId     string                 `protobuf:"bytes,4,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Title          string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Description    string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	PosterUrl      string                 `protobuf:"bytes,7,opt,name=poster_url,json=posterUrl,proto3" json:"poster_url,omitempty"`
	ReleaseDate    string                 `protobuf:"bytes,8,opt,name=release_date,json=releaseDate,proto3" json:"release_date,omitempty"` // YYYY-MM-DD
	CreatedAt      string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Content) Reset() {
	*x = Content{}
	mi := &file_catalog_system_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Content) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Content) ProtoMessage() {}

func (x *Content) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_system_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Content.ProtoReflect.Descriptor instead.
func (*Content) Descriptor() ([]byte, []int) {
	return file_catalog_system_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *Content) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Content) GetType() ContentType {
	if x != nil {
		return x.Type
	}
	return ContentType_CONTENT_TYPE_UNSPECIFIED
}

func (x *Content) GetExternalSource() string {
	if x != nil {
		return x.ExternalSource
	}
	return ""
}

func (x *Content) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *Content) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Content) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Content) GetPosterUrl() string {
	if x != nil {
		return x.PosterUrl
	}
	return ""
}

func (x *Content) GetReleaseDate() string {
	if x != nil {
		return x.ReleaseDate
	}
	return ""
}

func (x *Content) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Content) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type MovieDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	TmdbId        int32                  `protobuf:"varint,2,opt,name=tmdb_id,json=tmdbId,proto3" json:"tmdb_id,omitempty"`
	OriginalTitle string                 `protobuf:"bytes,3,opt,name=original_title,json=originalTitle,proto3" json:"original_title,omitempty"`
	Runtime       int32                  `protobuf:"varint,4,opt,name=runtime,proto3" json:"runtime,omitempty"`
	Tagline       string                 `protobuf:"bytes,5,opt,name=tagline,proto3" json:"tagline,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Budget        int64                  `protobuf:"varint,7,opt,name=budget,proto3" json:"budget,omitempty"`
	Revenue       int64                  `protobuf:"varint,8,opt,name=revenue,proto3" json:"revenue,omitempty"`
	Language      string                 `protobuf:"bytes,9,opt,name=language,proto3" json:"language,omitempty"`
	GenresJson    string                 `protobuf:"bytes,10,opt,name=genres_json,json=genresJson,proto3" json:"genres_json,omitempty"`
	CastJson      string                 `protobuf:"bytes,11,opt,name=cast_json,json=castJson,proto3" json:"cast_json,omitempty"`
	CrewJson      string                 `protobuf:"bytes,12,opt,name=crew_json,json=crewJson,proto3" json:"crew_json,omitempty"`
	ImagesJson    string                 `protobuf:"bytes,13,opt,name=images_json,json=imagesJson,proto3" json:"images_json,omitempty"`
	VideosJson    string                 `protobuf:"bytes,14,opt,name=videos_json,json=videosJson,proto3" json:"videos_json,omitempty"`
	RawJson       string                 `protobuf:"bytes,15,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovieDetails) Reset() {
	*x = MovieDetails{}
	mi := &file_catalog_system_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovieDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieDetails) ProtoMessage() {}

func (x *MovieDetails) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_system_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieDetails.ProtoReflect.Descriptor instead.
func (*MovieDetails) Descriptor() ([]byte, []int) {
	return file_catalog_system_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *MovieDetails) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *MovieDetails) GetTmdbId() int32 {
	if x != nil {
		return x.TmdbId
	}
	return 0
}

func (x *MovieDetails) GetOriginalTitle() string {
	if x != nil {
		return x.OriginalTitle
	}
	return ""
}

func (x *MovieDetails) GetRuntime() int32 {
	if x != nil {
		return x.Runtime
	}
	return 0
}

func (x *MovieDetails) GetTagline() string {
	if x != nil {
		return x.Tagline
	}
	return ""
}

func (x *MovieDetails) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MovieDetails) GetBudget() int64 {
	if x != nil {
		return x.Budget
	}
	return 0
}

func (x *MovieDetails) GetRevenue() int64 {
	if x != nil {
		return x.Revenue
	}
	return 0
}

func (x *MovieDetails) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *MovieDetails) GetGenresJson() string {
	if x != nil {
		return x.GenresJson
	}
	return ""
}

func (x *MovieDetails) GetCastJson() string {
	if x != nil {
		return x.CastJson
	}
	return ""
}

func (x *MovieDetails) GetCrewJson() string {
	if x != nil {
		return x.CrewJson
	}
	return ""
}

func (x *MovieDetails) GetImagesJson() string {
	if x != nil {
		return x.ImagesJson
	}
	return ""
}

func (x *MovieDetails) GetVideosJson() string {
	if x != nil {
		return x.VideosJson
	}
	return ""
}

func (x *MovieDetails) GetRawJson() string {
	if x != nil {
		return x.RawJson
	}
	return ""
}

type SeriesDetails struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ContentId        string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	TmdbId           int32                  `protobuf:"varint,2,opt,name=tmdb_id,json=tmdbId,proto3" json:"tmdb_id,omitempty"`
	OriginalName     string                 `protobuf:"bytes,3,opt,name=original_name,json=originalName,proto3" json:"original_name,omitempty"`
	Status           string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	FirstAirDate     string                 `protobuf:"bytes,5,opt,name=first_air_date,json=firstAirDate,proto3" json:"first_air_date,omitempty"`
	LastAirDate      string                 `protobuf:"bytes,6,opt,name=last_air_date,json=lastAirDate,proto3" json:"last_air_date,omitempty"`
	NumberOfSeasons  int32                  `protobuf:"varint,7,opt,name=number_of_seasons,json=numberOfSeasons,proto3" json:"number_of_seasons,omitempty"`
	NumberOfEpisodes int32                  `protobuf:"varint,8,opt,name=number_of_episodes,json=numberOfEpisodes,proto3" json:"number_of_episodes,omitempty"`
	Language         string                 `protobuf:"bytes,9,opt,name=language,proto3" json:"language,omitempty"`
	GenresJson       string                 `protobuf:"bytes,10,opt,name=genres_json,json=genresJson,proto3" json:"genres_json,omitempty"`
	NetworksJson     string                 `protobuf:"bytes,11,opt,name=networks_json,json=networksJson,proto3" json:"networks_json,omitempty"`
	CastJson         string                 `protobuf:"bytes,12,opt,name=cast_json,json=castJson,proto3" json:"cast_json,omitempty"`
	ImagesJson       string                 `protobuf:"bytes,13,opt,name=images_json,json=imagesJson,proto3" json:"images_json,omitempty"`
	VideosJson       string                 `protobuf:"bytes,14,opt,name=videos_json,json=videosJson,proto3" json:"videos_json,omitempty"`
	RawJson          string                 `protobuf:"bytes,15,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SeriesDetails) Reset() {
	*x = SeriesDetails{}
	mi := &file_catalog_system_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeriesDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeriesDetails) ProtoMessage() {}

func (x *SeriesDetails) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_system_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeriesDetails.ProtoReflect.Descriptor instead.
func (*SeriesDetails) Descriptor() ([]byte, []int) {
	return file_catalog_system_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *SeriesDetails) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *SeriesDetails) GetTmdbId() int32 {
	if x != nil {
		return x.TmdbId
	}
	return 0
}

func (x *SeriesDetails) GetOriginalName() string {
	if x != nil {
		return x.OriginalName
	}
	return ""
}

func (x *SeriesDetails) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SeriesDetails) GetFirstAirDate() string {
	if x != nil {
		return x.FirstAirDate
	}
	return ""
}

func (x *SeriesDetails) GetLastAirDate() string {
	if x != nil {
		return x.LastAirDate
	}
	return ""
}

func (x *SeriesDetails) GetNumberOfSeasons() int32 {
	if x != nil {
		return x.NumberOfSeasons
	}
	return 0
}

func (x *SeriesDetails) GetNumberOfEpisodes() int32 {
	if x != nil {
		return x.NumberOfEpisodes
	}
	return 0
}

func (x *SeriesDetails) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *SeriesDetails) GetGenresJson() string {
	if x != nil {
		return x.GenresJson
	}
	return ""
}

func (x *SeriesDetails) GetNetworksJson() string {
	if x != nil {
		return x.NetworksJson
	}
	return ""
}

func (x *SeriesDetails) GetCastJson() string {
	if x != nil {
		return x.CastJson
	}
	return ""
}

func (x *SeriesDetails) GetImagesJson() string {
	if x != nil {
		return x.ImagesJson
	}
	return ""
}

func (x *SeriesDetails) GetVideosJson() string {
	if x != nil {
		return x.VideosJson
	}
	return ""
}

func (x *SeriesDetails) GetRawJson() string {
	if x != nil {
		return x.RawJson
	}
	return ""
}

type AnimeDetails struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContentId       string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	AnilistId       int32                  `protobuf:"varint,2,opt,name=anilist_id,json=anilistId,proto3" json:"anilist_id,omitempty"`
	MalId           int32                  `protobuf:"varint,3,opt,name=mal_id,json=malId,proto3" json:"mal_id,omitempty"`
	OriginalTitle   string                 `protobuf:"bytes,4,opt,name=original_title,json=originalTitle,proto3" json:"original_title,omitempty"`
	Format          string                 `protobuf:"bytes,5,opt,name=format,proto3" json:"format,omitempty"` // TV | MOVIE | OVA | ONA
	Status          string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"` // FINISHED | RELEASING
	Season          string                 `protobuf:"bytes,7,opt,name=season,proto3" json:"season,omitempty"` // WINTER | SPRING | SUMMER | FALL
	SeasonYear      int32                  `protobuf:"varint,8,opt,name=season_year,json=seasonYear,proto3" json:"season_year,omitempty"`
	EpisodesCount   int32                  `protobuf:"varint,9,opt,name=episodes_count,json=episodesCount,proto3" json:"episodes_count,omitempty"`
	EpisodeDuration int32                  `protobuf:"varint,10,opt,name=episode_duration,json=episodeDuration,proto3" json:"episode_duration,omitempty"`
	StartDate       string                 `protobuf:"bytes,11,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate         string                 `protobuf:"bytes,12,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Language        string                 `protobuf:"bytes,13,opt,name=language,proto3" json:"language,omitempty"`
	GenresJson      string                 `protobuf:"bytes,14,opt,name=genres_json,json=genresJson,proto3" json:"genres_json,omitempty"`
	TagsJson        string                 `protobuf:"bytes,15,opt,name=tags_json,json=tagsJson,proto3" json:"tags_json,omitempty"`
	StudiosJson     string                 `protobuf:"bytes,16,opt,name=studios_json,json=studiosJson,proto3" json:"studios_json,omitempty"`
	CharactersJson  string                 `protobuf:"bytes,17,opt,name=characters_json,json=charactersJson,proto3" json:"characters_json,omitempty"`
	VoiceActorsJson string                 `protobuf:"bytes,18,opt,name=voice_actors_json,json=voiceActorsJson,proto3" json:"voice_actors_json,omitempty"`
	MeanScore       int32                  `protobuf:"varint,19,opt,name=mean_score,json=meanScore,proto3" json:"mean_score,omitempty"`
	Popularity      int32                  `protobuf:"varint,20,opt,name=popularity,proto3" json:"popularity,omitempty"`
	Favourites      int32                  `protobuf:"varint,21,opt,name=favourites,proto3" json:"favourites,omitempty"`
	TrailerUrl      string                 `protobuf:"bytes,22,opt,name=trailer_url,json=trailerUrl,proto3" json:"trailer_url,omitempty"`
	RawJson         string                 `protobuf:"bytes,23,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AnimeDetails) Reset() {
	*x = AnimeDetails{}
	mi := &file_catalog_system_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnimeDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnimeDetails) ProtoMessage() {}

func (x *AnimeDetails) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_system_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnimeDetails.ProtoReflect.Descriptor instead.
func (*AnimeDetails) Descriptor() ([]byte, []int) {
	return file_catalog_system_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *AnimeDetails) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *AnimeDetails) GetAnilistId() int32 {
	if x != nil {
		return x.AnilistId
	}
	return 0
}

func (x *AnimeDetails) GetMalId() int32 {
	if x != nil {
		return x.MalId
	}
	return 0
}

func (x *AnimeDetails) GetOriginalTitle() string {
	if x != nil {
		return x.OriginalTitle
	}
	return ""
}

func (x *AnimeDetails) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *AnimeDetails) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AnimeDetails) GetSeason() string {
	if x != nil {
		return x.Season
	}
	return ""
}

func (x *AnimeDetails) GetSeasonYear() int32 {
	if x != nil {
		return x.SeasonYear
	}
	return 0
}

func (x *AnimeDetails) GetEpisodesCount() int32 {
	if x != nil {
		return x.EpisodesCount
	}
	return 0
}

func (x *AnimeDetails) GetEpisodeDuration() int32 {
	if x != nil {
		return x.EpisodeDuration
	}
	return 0
}

func (x *AnimeDetails) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *AnimeDetails) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *AnimeDetails) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *AnimeDetails) GetGenresJson() string {
	if x != nil {
		return x.GenresJson
	}
	return ""
}

func (x *AnimeDetails) GetTagsJson() string {
	if x != nil {
		return x.TagsJson
	}
	return ""
}

func (x *AnimeDetails) GetStudiosJson() string {
	if x != nil {
		return x.StudiosJson
	}
	return ""
}

func (x *AnimeDetails) GetCharactersJson() string {
	if x != nil {
		return x.CharactersJson
	}
	return ""
}

func (x *AnimeDetails) GetVoiceActorsJson() string {
	if x != nil {
		return x.VoiceActorsJson
	}
	return ""
}

func (x *AnimeDetails) GetMeanScore() int32 {
	if x != nil {
		return x.MeanScore
	}
	return 0
}

func (x *AnimeDetails) GetPopularity() int32 {
	if x != nil {
		return x.Popularity
	}
	return 0
}

func (x *AnimeDetails) GetFavourites() int32 {
	if x != nil {
		return x.Favourites
	}
	return 0
}

func (x *AnimeDetails) GetTrailerUrl() string {
	if x != nil {
		return x.TrailerUrl
	}
	return ""
}

func (x *AnimeDetails) GetRawJson() string {
	if x != nil {
		return x.RawJson
	}
	return ""
}

type GameDetails struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContentId       string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	IgdbId          int32                  `protobuf:"varint,2,opt,name=igdb_id,json=igdbId,proto3" json:"igdb_id,omitempty"`
	Rating          float64                `protobuf:"fixed64,3,opt,name=rating,proto3" json:"rating,omitempty"`
	GenresJson      string                 `protobuf:"bytes,4,opt,name=genres_json,json=genresJson,proto3" json:"genres_json,omitempty"`
	PlatformsJson   string                 `protobuf:"bytes,5,opt,name=platforms_json,json=platformsJson,proto3" json:"platforms_json,omitempty"`
	DevelopersJson  string                 `protobuf:"bytes,6,opt,name=developers_json,json=developersJson,proto3" json:"developers_json,omitempty"`
	PublishersJson  string                 `protobuf:"bytes,7,opt,name=publishers_json,json=publishersJson,proto3" json:"publishers_json,omitempty"`
	ScreenshotsJson string                 `protobuf:"bytes,8,opt,name=screenshots_json,json=screenshotsJson,proto3" json:"screenshots_json,omitempty"`
	RawJson         string                 `protobuf:"bytes,9,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GameDetails) Reset() {
	*x = GameDetails{}
	mi := &file_catalog_system_catalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameDetails) ProtoMessage() {}

func (x *GameDetails) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_system_catalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameDetails.ProtoReflect.Descriptor instead.
func (*GameDetails) Descriptor() ([]byte, []int) {
	return file_catalog_system_catalog_proto_rawDescGZIP(), []int{4}
}

func (x *GameDetails) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *GameDetails) GetIgdbId() int32 {
	if x != nil {
		return x.IgdbId
	}
	return 0
}

func (x *GameDetails) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *GameDetails) GetGenresJson() string {
	if x != nil {
		return x.GenresJson
	}
	return ""
}

func (x *GameDetails) GetPlatformsJson() string {
	if x != nil {
		return x.PlatformsJson
	}
	return ""
}

func (x *GameDetails) GetDevelopersJson() string {
	if x != nil {
		return x.DevelopersJson
	}
	return ""
}

func (x *GameDetails) GetPublishersJson() string {
	if x != nil {
		return x.PublishersJson
	}
	return ""
}

func (x *GameDetails) GetScreenshotsJson() string {
	if x != nil {
		return x.ScreenshotsJson
	}
	return ""
}

func (x *GameDetails) GetRawJson() string {
	if x != nil {
		return x.RawJson
	}
	return ""
}

type BookDetails struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ContentId      string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	Isbn_10        string                 `protobuf:"bytes,2,opt,name=isbn_10,json=isbn10,proto3" json:"isbn_10,omitempty"`
	Isbn_13        string                 `protobuf:"bytes,3,opt,name=isbn_13,json=isbn13,proto3" json:"isbn_13,omitempty"`
	Language       string                 `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	Pages          int32                  `protobuf:"varint,5,opt,name=pages,proto3" json:"pages,omitempty"`
	PublishDate    string                 `protobuf:"bytes,6,opt,name=publish_date,json=publishDate,proto3" json:"publish_date,omitempty"`
	AuthorsJson    string                 `protobuf:"bytes,7,opt,name=authors_json,json=authorsJson,proto3" json:"authors_json,omitempty"`
	PublishersJson string                 `protobuf:"bytes,8,opt,name=publishers_json,json=publishersJson,proto3" json:"publishers_json,omitempty"`
	GenresJson     string                 `protobuf:"bytes,9,opt,name=genres_json,json=genresJson,proto3" json:"genres_json,omitempty"`
	RawJson        string                 `protobuf:"bytes,10,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BookDetails) Reset() {
	*x = BookDetails{}
	mi := &file_catalog_system_catalog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookDetails) ProtoMessage() {}

func (x *BookDetails) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_system_catalog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookDetails.ProtoReflect.Descriptor instead.
func (*BookDetails) Descriptor() ([]byte, []int) {
	return file_catalog_system_catalog_proto_rawDescGZIP(), []int{5}
}

func (x *BookDetails) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *BookDetails) GetIsbn_10() string {
	if x != nil {
		return x.Isbn_10
	}
	return ""
}

func (x *BookDetails) GetIsbn_13() string {
	if x != nil {
		return x.Isbn_13
	}
	return ""
}

func (x *BookDetails) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *BookDetails) GetPages() int32 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *BookDetails) GetPublishDate() string {
	if x != nil {
		return x.PublishDate
	}
	return ""
}

func (x *BookDetails) GetAuthorsJson() string {
	if x != nil {
		return x.AuthorsJson
	}
	return ""
}

func (x *BookDetails) GetPublishersJson() string {
	if x != nil {
		return x.PublishersJson
	}
	return ""
}

func (x *BookDetails) GetGenresJson() string {
	if x != nil {
		return x.GenresJson
	}
	return ""
}

func (x *BookDetails) GetRawJson() string {
	if x != nil {
		return x.RawJson
	}
	return ""
}

type GetContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContentRequest) Reset() {
	*x = GetContentRequest{}
	mi := &file_catalog_system_catalog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentRequest) ProtoMessage() {}

func (x *GetContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_system_catalog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentRequest.ProtoReflect.Descriptor instead.
func (*GetContentRequest) Descriptor() ([]byte, []int) {
	return file_catalog_system_catalog_proto_rawDescGZIP(), []int{6}
}

func (x *GetContentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       *Content               `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContentResponse) Reset() {
	*x = GetContentResponse{}
	mi := &file_catalog_system_catalog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentResponse) ProtoMessage() {}

func (x *GetContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_system_catalog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentResponse.ProtoReflect.Descriptor instead.
func (*GetContentResponse) Descriptor() ([]byte, []int) {
	return file_catalog_system_catalog_proto_rawDescGZIP(), []int{7}
}

func (x *GetContentResponse) GetContent() *Content {
	if x != nil {
		return x.Content
	}
	return nil
}

type FindContentByExternalRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ExternalSource string                 `protobuf:"bytes,1,opt,name=external_source,json=externalSource,proto3" json:"external_source,omitempty"`
	ExternalId     string                 `protobuf:"bytes,2,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FindContentByExternalRequest) Reset() {
	*x = FindContentByExternalRequest{}
	mi := &file_catalog_system_catalog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindContentByExternalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindContentByExternalRequest) ProtoMessage() {}

func (x *FindContentByExternalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_system_catalog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindContentByExternalRequest.ProtoReflect.Descriptor instead.
func (*FindContentByExternalRequest) Descriptor() ([]byte, []int) {
	return file_catalog_system_catalog_proto_rawDescGZIP(), []int{8}
}

func (x *FindContentByExternalRequest) GetExternalSource() string {
	if x != nil {
		return x.ExternalSource
	}
	return ""
}

func (x *FindContentByExternalRequest) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

type FindContentByExternalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       *Content               `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindContentByExternalResponse) Reset() {
	*x = FindContentByExternalResponse{}
	mi := &file_catalog_system_catalog_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindContentByExternalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindContentByExternalResponse) ProtoMessage() {}

func (x *FindContentByExternalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_system_catalog_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindContentByExternalResponse.ProtoReflect.Descriptor instead.
func (*FindContentByExternalResponse) Descriptor() ([]byte, []int) {
	return file_catalog_system_catalog_proto_rawDescGZIP(), []int{9}
}

func (x *FindContentByExternalResponse) GetContent() *Content {
	if x != nil {
		return x.Content
	}
	return nil
}

type CreateContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       *Content               `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateContentRequest) Reset() {
	*x = CreateContentRequest{}
	mi := &file_catalog_system_catalog_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContentRequest) ProtoMessage() {}

func (x *CreateContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_system_catalog_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContentRequest.ProtoReflect.Descriptor instead.
func (*CreateContentRequest) Descriptor() ([]byte, []int) {
	return file_catalog_system_catalog_proto_rawDescGZIP(), []int{10}
}

func (x *CreateContentRequest) GetContent() *Content {
	if x != nil {
		return x.Content
	}
	return nil
}

type CreateContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       *Content               `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateContentResponse) Reset() {
	*x = CreateContentResponse{}
	mi := &file_catalog_system_catalog_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContentResponse) ProtoMessage() {}

func (x *CreateContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_system_catalog_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContentResponse.ProtoReflect.Descriptor instead.
func (*CreateContentResponse) Descriptor() ([]byte, []int) {
	return file_catalog_system_catalog_proto_rawDescGZIP(), []int{11}
}

func (x *CreateContentResponse) GetContent() *Content {
	if x != nil {
		return x.Content
	}
	return nil
}

type UpdateContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       *Content               `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateContentRequest) Reset() {
	*x = UpdateContentRequest{}
	mi := &file_catalog_system_catalog_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateContentRequest) ProtoMessage() {}

func (x *UpdateContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_system_catalog_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateContentRequest.ProtoReflect.Descriptor instead.
func (*UpdateContentRequest) Descriptor() ([]byte, []int) {
	return file_catalog_system_catalog_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateContentRequest) GetContent() *Content {
	if x != nil {
		return x.Content
	}
	return nil
}

type UpdateContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       *Content               `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateContentResponse) Reset() {
	*x = UpdateContentResponse{}
	mi := &file_catalog_system_catalog_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateContentResponse) ProtoMessage() {}

func (x *UpdateContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_system_catalog_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateContentResponse.ProtoReflect.Descriptor instead.
func (*UpdateContentResponse) Descriptor() ([]byte, []int) {
	return file_catalog_system_catalog_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateContentResponse) GetContent() *Content {
	if x != nil {
		return x.Content
	}
	return nil
}

type GetMovieDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMovieDetailsRequest) Reset() {
	*x = GetMovieDetailsRequest{}
	mi := &file_catalog_system_catalog_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMovieDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMovieDetailsRequest) ProtoMessage() {}

func (x *GetMovieDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_system_catalog_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMovieDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetMovieDetailsRequest) Descriptor() ([]byte, []int) {
	return file_catalog_system_catalog_proto_rawDescGZIP(), []int{14}
}

func (x *GetMovieDetailsRequest) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

type GetMovieDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Details       *MovieDetails          `protobuf:"bytes,1,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMovieDetailsResponse) Reset() {
	*x = GetMovieDetailsResponse{}
	mi := &file_catalog_system_catalog_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMovieDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMovieDetailsResponse) ProtoMessage() {}

func (x *GetMovieDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_system_catalog_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMovieDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetMovieDetailsResponse) Descriptor() ([]byte, []int) {
	return file_catalog_system_catalog_proto_rawDescGZIP(), []int{15}
}

func (x *GetMovieDetailsResponse) GetDetails() *MovieDetails {
	if x != nil {
		return x.Details
	}
	return nil
}

type GetAnimeDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnimeDetailsRequest) Reset() {
	*x = GetAnimeDetailsRequest{}
	mi := &file_catalog_system_catalog_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnimeDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnimeDetailsRequest) ProtoMessage() {}

func (x *GetAnimeDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_system_catalog_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnimeDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetAnimeDetailsRequest) Descriptor() ([]byte, []int) {
	return file_catalog_system_catalog_proto_rawDescGZIP(), []int{16}
}

func (x *GetAnimeDetailsRequest) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

type GetAnimeDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Details       *AnimeDetails          `protobuf:"bytes,1,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnimeDetailsResponse) Reset() {
	*x = GetAnimeDetailsResponse{}
	mi := &file_catalog_system_catalog_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnimeDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnimeDetailsResponse) ProtoMessage() {}

func (x *GetAnimeDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_system_catalog_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnimeDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetAnimeDetailsResponse) Descriptor() ([]byte, []int) {
	return file_catalog_system_catalog_proto_rawDescGZIP(), []int{17}
}

func (x *GetAnimeDetailsResponse) GetDetails() *AnimeDetails {
	if x != nil {
		return x.Details
	}
	return nil
}

type GetGameDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameDetailsRequest) Reset() {
	*x = GetGameDetailsRequest{}
	mi := &file_catalog_system_catalog_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameDetailsRequest) ProtoMessage() {}

func (x *GetGameDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_system_catalog_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetGameDetailsRequest) Descriptor() ([]byte, []int) {
	return file_catalog_system_catalog_proto_rawDescGZIP(), []int{18}
}

func (x *GetGameDetailsRequest) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

type GetGameDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Details       *GameDetails           `protobuf:"bytes,1,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameDetailsResponse) Reset() {
	*x = GetGameDetailsResponse{}
	mi := &file_catalog_system_catalog_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameDetailsResponse) ProtoMessage() {}

func (x *GetGameDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_system_catalog_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetGameDetailsResponse) Descriptor() ([]byte, []int) {
	return file_catalog_system_catalog_proto_rawDescGZIP(), []int{19}
}

func (x *GetGameDetailsResponse) GetDetails() *GameDetails {
	if x != nil {
		return x.Details
	}
	return nil
}

type GetSeriesDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeriesDetailsRequest) Reset() {
	*x = GetSeriesDetailsRequest{}
	mi := &file_catalog_system_catalog_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeriesDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeriesDetailsRequest) ProtoMessage() {}

func (x *GetSeriesDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_system_catalog_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeriesDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetSeriesDetailsRequest) Descriptor() ([]byte, []int) {
	return file_catalog_system_catalog_proto_rawDescGZIP(), []int{20}
}

func (x *GetSeriesDetailsRequest) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

type GetSeriesDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Details       *SeriesDetails         `protobuf:"bytes,1,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeriesDetailsResponse) Reset() {
	*x = GetSeriesDetailsResponse{}
	mi := &file_catalog_system_catalog_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeriesDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeriesDetailsResponse) ProtoMessage() {}

func (x *GetSeriesDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_system_catalog_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeriesDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetSeriesDetailsResponse) Descriptor() ([]byte, []int) {
	return file_catalog_system_catalog_proto_rawDescGZIP(), []int{21}
}

func (x *GetSeriesDetailsResponse) GetDetails() *SeriesDetails {
	if x != nil {
		return x.Details
	}
	return nil
}

type GetBookDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookDetailsRequest) Reset() {
	*x = GetBookDetailsRequest{}
	mi := &file_catalog_system_catalog_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookDetailsRequest) ProtoMessage() {}

func (x *GetBookDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_system_catalog_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetBookDetailsRequest) Descriptor() ([]byte, []int) {
	return file_catalog_system_catalog_proto_rawDescGZIP(), []int{22}
}

func (x *GetBookDetailsRequest) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

type GetBookDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Details       *BookDetails           `protobuf:"bytes,1,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookDetailsResponse) Reset() {
	*x = GetBookDetailsResponse{}
	mi := &file_catalog_system_catalog_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookDetailsResponse) ProtoMessage() {}

func (x *GetBookDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_system_catalog_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetBookDetailsResponse) Descriptor() ([]byte, []int) {
	return file_catalog_system_catalog_proto_rawDescGZIP(), []int{23}
}

func (x *GetBookDetailsResponse) GetDetails() *BookDetails {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_catalog_system_catalog_proto protoreflect.FileDescriptor

const file_catalog_system_catalog_proto_rawDesc = "" +
	"\n" +
	"\x1ccatalog-system/catalog.proto\x12\acatalog\"\xc5\x02\n" +
	"\aContent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x04type\x18\x02 \x01(\x0e2\x14.catalog.ContentTypeR\x04type\x12'\n" +
	"\x0fexternal_source\x18\x03 \x01(\tR\x0eexternalSource\x12\x1f\n" +
	"\vexternal_id\x18\x04 \x01(\tR\n" +
	"externalId\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"poster_url\x18\a \x01(\tR\tposterUrl\x12!\n" +
	"\frelease_date\x18\b \x01(\tR\vreleaseDate\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\"\xbf\x03\n" +
	"\fMovieDetails\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\x12\x17\n" +
	"\atmdb_id\x18\x02 \x01(\x05R\x06tmdbId\x12%\n" +
	"\x0eoriginal_title\x18\x03 \x01(\tR\roriginalTitle\x12\x18\n" +
	"\aruntime\x18\x04 \x01(\x05R\aruntime\x12\x18\n" +
	"\atagline\x18\x05 \x01(\tR\atagline\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x16\n" +
	"\x06budget\x18\a \x01(\x03R\x06budget\x12\x18\n" +
	"\arevenue\x18\b \x01(\x03R\arevenue\x12\x1a\n" +
	"\blanguage\x18\t \x01(\tR\blanguage\x12\x1f\n" +
	"\vgenres_json\x18\n" +
	" \x01(\tR\n" +
	"genresJson\x12\x1b\n" +
	"\tcast_json\x18\v \x01(\tR\bcastJson\x12\x1b\n" +
	"\tcrew_json\x18\f \x01(\tR\bcrewJson\x12\x1f\n" +
	"\vimages_json\x18\r \x01(\tR\n" +
	"imagesJson\x12\x1f\n" +
	"\vvideos_json\x18\x0e \x01(\tR\n" +
	"videosJson\x12\x19\n" +
	"\braw_json\x18\x0f \x01(\tR\arawJson\"\x84\x04\n" +
	"\rSeriesDetails\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\x12\x17\n" +
	"\atmdb_id\x18\x02 \x01(\x05R\x06tmdbId\x12#\n" +
	"\roriginal_name\x18\x03 \x01(\tR\foriginalName\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12$\n" +
	"\x0efirst_air_date\x18\x05 \x01(\tR\ffirstAirDate\x12\"\n" +
	"\rlast_air_date\x18\x06 \x01(\tR\vlastAirDate\x12*\n" +
	"\x11number_of_seasons\x18\a \x01(\x05R\x0fnumberOfSeasons\x12,\n" +
	"\x12number_of_episodes\x18\b \x01(\x05R\x10numberOfEpisodes\x12\x1a\n" +
	"\blanguage\x18\t \x01(\tR\blanguage\x12\x1f\n" +
	"\vgenres_json\x18\n" +
	" \x01(\tR\n" +
	"genresJson\x12#\n" +
	"\rnetworks_json\x18\v \x01(\tR\fnetworksJson\x12\x1b\n" +
	"\tcast_json\x18\f \x01(\tR\bcastJson\x12\x1f\n" +
	"\vimages_json\x18\r \x01(\tR\n" +
	"imagesJson\x12\x1f\n" +
	"\vvideos_json\x18\x0e \x01(\tR\n" +
	"videosJson\x12\x19\n" +
	"\braw_json\x18\x0f \x01(\tR\arawJson\"\xec\x05\n" +
	"\fAnimeDetails\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\x12\x1d\n" +
	"\n" +
	"anilist_id\x18\x02 \x01(\x05R\tanilistId\x12\x15\n" +
	"\x06mal_id\x18\x03 \x01(\x05R\x05malId\x12%\n" +
	"\x0eoriginal_title\x18\x04 \x01(\tR\roriginalTitle\x12\x16\n" +
	"\x06format\x18\x05 \x01(\tR\x06format\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x16\n" +
	"\x06season\x18\a \x01(\tR\x06season\x12\x1f\n" +
	"\vseason_year\x18\b \x01(\x05R\n" +
	"seasonYear\x12%\n" +
	"\x0eepisodes_count\x18\t \x01(\x05R\repisodesCount\x12)\n" +
	"\x10episode_duration\x18\n" +
	" \x01(\x05R\x0fepisodeDuration\x12\x1d\n" +
	"\n" +
	"start_date\x18\v \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\f \x01(\tR\aendDate\x12\x1a\n" +
	"\blanguage\x18\r \x01(\tR\blanguage\x12\x1f\n" +
	"\vgenres_json\x18\x0e \x01(\tR\n" +
	"genresJson\x12\x1b\n" +
	"\ttags_json\x18\x0f \x01(\tR\btagsJson\x12!\n" +
	"\fstudios_json\x18\x10 \x01(\tR\vstudiosJson\x12'\n" +
	"\x0fcharacters_json\x18\x11 \x01(\tR\x0echaractersJson\x12*\n" +
	"\x11voice_actors_json\x18\x12 \x01(\tR\x0fvoiceActorsJson\x12\x1d\n" +
	"\n" +
	"mean_score\x18\x13 \x01(\x05R\tmeanScore\x12\x1e\n" +
	"\n" +
	"popularity\x18\x14 \x01(\x05R\n" +
	"popularity\x12\x1e\n" +
	"\n" +
	"favourites\x18\x15 \x01(\x05R\n" +
	"favourites\x12\x1f\n" +
	"\vtrailer_url\x18\x16 \x01(\tR\n" +
	"trailerUrl\x12\x19\n" +
	"\braw_json\x18\x17 \x01(\tR\arawJson\"\xbd\x02\n" +
	"\vGameDetails\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\x12\x17\n" +
	"\aigdb_id\x18\x02 \x01(\x05R\x06igdbId\x12\x16\n" +
	"\x06rating\x18\x03 \x01(\x01R\x06rating\x12\x1f\n" +
	"\vgenres_json\x18\x04 \x01(\tR\n" +
	"genresJson\x12%\n" +
	"\x0eplatforms_json\x18\x05 \x01(\tR\rplatformsJson\x12'\n" +
	"\x0fdevelopers_json\x18\x06 \x01(\tR\x0edevelopersJson\x12'\n" +
	"\x0fpublishers_json\x18\a \x01(\tR\x0epublishersJson\x12)\n" +
	"\x10screenshots_json\x18\b \x01(\tR\x0fscreenshotsJson\x12\x19\n" +
	"\braw_json\x18\t \x01(\tR\arawJson\"\xbb\x02\n" +
	"\vBookDetails\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\x12\x17\n" +
	"\aisbn_10\x18\x02 \x01(\tR\x06isbn10\x12\x17\n" +
	"\aisbn_13\x18\x03 \x01(\tR\x06isbn13\x12\x1a\n" +
	"\blanguage\x18\x04 \x01(\tR\blanguage\x12\x14\n" +
	"\x05pages\x18\x05 \x01(\x05R\x05pages\x12!\n" +
	"\fpublish_date\x18\x06 \x01(\tR\vpublishDate\x12!\n" +
	"\fauthors_json\x18\a \x01(\tR\vauthorsJson\x12'\n" +
	"\x0fpublishers_json\x18\b \x01(\tR\x0epublishersJson\x12\x1f\n" +
	"\vgenres_json\x18\t \x01(\tR\n" +
	"genresJson\x12\x19\n" +
	"\braw_json\x18\n" +
	" \x01(\tR\arawJson\"#\n" +
	"\x11GetContentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"@\n" +
	"\x12GetContentResponse\x12*\n" +
	"\acontent\x18\x01 \x01(\v2\x10.catalog.ContentR\acontent\"h\n" +
	"\x1cFindContentByExternalRequest\x12'\n" +
	"\x0fexternal_source\x18\x01 \x01(\tR\x0eexternalSource\x12\x1f\n" +
	"\vexternal_id\x18\x02 \x01(\tR\n" +
	"externalId\"K\n" +
	"\x1dFindContentByExternalResponse\x12*\n" +
	"\acontent\x18\x01 \x01(\v2\x10.catalog.ContentR\acontent\"B\n" +
	"\x14CreateContentRequest\x12*\n" +
	"\acontent\x18\x01 \x01(\v2\x10.catalog.ContentR\acontent\"C\n" +
	"\x15CreateContentResponse\x12*\n" +
	"\acontent\x18\x01 \x01(\v2\x10.catalog.ContentR\acontent\"B\n" +
	"\x14UpdateContentRequest\x12*\n" +
	"\acontent\x18\x01 \x01(\v2\x10.catalog.ContentR\acontent\"C\n" +
	"\x15UpdateContentResponse\x12*\n" +
	"\acontent\x18\x01 \x01(\v2\x10.catalog.ContentR\acontent\"7\n" +
	"\x16GetMovieDetailsRequest\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\"J\n" +
	"\x17GetMovieDetailsResponse\x12/\n" +
	"\adetails\x18\x01 \x01(\v2\x15.catalog.MovieDetailsR\adetails\"7\n" +
	"\x16GetAnimeDetailsRequest\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\"J\n" +
	"\x17GetAnimeDetailsResponse\x12/\n" +
	"\adetails\x18\x01 \x01(\v2\x15.catalog.AnimeDetailsR\adetails\"6\n" +
	"\x15GetGameDetailsRequest\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\"H\n" +
	"\x16GetGameDetailsResponse\x12.\n" +
	"\adetails\x18\x01 \x01(\v2\x14.catalog.GameDetailsR\adetails\"8\n" +
	"\x17GetSeriesDetailsRequest\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\"L\n" +
	"\x18GetSeriesDetailsResponse\x120\n" +
	"\adetails\x18\x01 \x01(\v2\x16.catalog.SeriesDetailsR\adetails\"6\n" +
	"\x15GetBookDetailsRequest\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\"H\n" +
	"\x16GetBookDetailsResponse\x12.\n" +
	"\adetails\x18\x01 \x01(\v2\x14.catalog.BookDetailsR\adetails*a\n" +
	"\vContentType\x12\x1c\n" +
	"\x18CONTENT_TYPE_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05MOVIE\x10\x01\x12\n" +
	"\n" +
	"\x06SERIES\x10\x02\x12\t\n" +
	"\x05ANIME\x10\x03\x12\b\n" +
	"\x04GAME\x10\x04\x12\b\n" +
	"\x04BOOK\x10\x052\x8a\x06\n" +
	"\x0eCatalogService\x12N\n" +
	"\rCreateContent\x12\x1d.catalog.CreateContentRequest\x1a\x1e.catalog.CreateContentResponse\x12E\n" +
	"\n" +
	"GetContent\x12\x1a.catalog.GetContentRequest\x1a\x1b.catalog.GetContentResponse\x12N\n" +
	"\rUpdateContent\x12\x1d.catalog.UpdateContentRequest\x1a\x1e.catalog.UpdateContentResponse\x12f\n" +
	"\x15FindContentByExternal\x12%.catalog.FindContentByExternalRequest\x1a&.catalog.FindContentByExternalResponse\x12T\n" +
	"\x0fGetMovieDetails\x12\x1f.catalog.GetMovieDetailsRequest\x1a .catalog.GetMovieDetailsResponse\x12T\n" +
	"\x0fGetAnimeDetails\x12\x1f.catalog.GetAnimeDetailsRequest\x1a .catalog.GetAnimeDetailsResponse\x12Q\n" +
	"\x0eGetGameDetails\x12\x1e.catalog.GetGameDetailsRequest\x1a\x1f.catalog.GetGameDetailsResponse\x12W\n" +
	"\x10GetSeriesDetails\x12 .catalog.GetSeriesDetailsRequest\x1a!.catalog.GetSeriesDetailsResponse\x12Q\n" +
	"\x0eGetBookDetails\x12\x1e.catalog.GetBookDetailsRequest\x1a\x1f.catalog.GetBookDetailsResponseB;Z9catalog-system-microservice/internal/pb/catalog;catalogpbb\x06proto3"

var (
	file_catalog_system_catalog_proto_rawDescOnce sync.Once
	file_catalog_system_catalog_proto_rawDescData []byte
)

func file_catalog_system_catalog_proto_rawDescGZIP() []byte {
	file_catalog_system_catalog_proto_rawDescOnce.Do(func() {
		file_catalog_system_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_system_catalog_proto_rawDesc), len(file_catalog_system_catalog_proto_rawDesc)))
	})
	return file_catalog_system_catalog_proto_rawDescData
}

var file_catalog_system_catalog_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_catalog_system_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_catalog_system_catalog_proto_goTypes = []any{
	(ContentType)(0),                      // 0: catalog.ContentType
	(*Content)(nil),                       // 1: catalog.Content
	(*MovieDetails)(nil),                  // 2: catalog.MovieDetails
	(*SeriesDetails)(nil),                 // 3: catalog.SeriesDetails
	(*AnimeDetails)(nil),                  // 4: catalog.AnimeDetails
	(*GameDetails)(nil),                   // 5: catalog.GameDetails
	(*BookDetails)(nil),                   // 6: catalog.BookDetails
	(*GetContentRequest)(nil),             // 7: catalog.GetContentRequest
	(*GetContentResponse)(nil),            // 8: catalog.GetContentResponse
	(*FindContentByExternalRequest)(nil),  // 9: catalog.FindContentByExternalRequest
	(*FindContentByExternalResponse)(nil), // 10: catalog.FindContentByExternalResponse
	(*CreateContentRequest)(nil),          // 11: catalog.CreateContentRequest
	(*CreateContentResponse)(nil),         // 12: catalog.CreateContentResponse
	(*UpdateContentRequest)(nil),          // 13: catalog.UpdateContentRequest
	(*UpdateContentResponse)(nil),         // 14: catalog.UpdateContentResponse
	(*GetMovieDetailsRequest)(nil),        // 15: catalog.GetMovieDetailsRequest
	(*GetMovieDetailsResponse)(nil),       // 16: catalog.GetMovieDetailsResponse
	(*GetAnimeDetailsRequest)(nil),        // 17: catalog.GetAnimeDetailsRequest
	(*GetAnimeDetailsResponse)(nil),       // 18: catalog.GetAnimeDetailsResponse
	(*GetGameDetailsRequest)(nil),         // 19: catalog.GetGameDetailsRequest
	(*GetGameDetailsResponse)(nil),        // 20: catalog.GetGameDetailsResponse
	(*GetSeriesDetailsRequest)(nil),       // 21: catalog.GetSeriesDetailsRequest
	(*GetSeriesDetailsResponse)(nil),      // 22: catalog.GetSeriesDetailsResponse
	(*GetBookDetailsRequest)(nil),         // 23: catalog.GetBookDetailsRequest
	(*GetBookDetailsResponse)(nil),        // 24: catalog.GetBookDetailsResponse
}
var file_catalog_system_catalog_proto_depIdxs = []int32{
	0,  // 0: catalog.Content.type:type_name -> catalog.ContentType
	1,  // 1: catalog.GetContentResponse.content:type_name -> catalog.Content
	1,  // 2: catalog.FindContentByExternalResponse.content:type_name -> catalog.Content
	1,  // 3: catalog.CreateContentRequest.content:type_name -> catalog.Content
	1,  // 4: catalog.CreateContentResponse.content:type_name -> catalog.Content
	1,  // 5: catalog.UpdateContentRequest.content:type_name -> catalog.Content
	1,  // 6: catalog.UpdateContentResponse.content:type_name -> catalog.Content
	2,  // 7: catalog.GetMovieDetailsResponse.details:type_name -> catalog.MovieDetails
	4,  // 8: catalog.GetAnimeDetailsResponse.details:type_name -> catalog.AnimeDetails
	5,  // 9: catalog.GetGameDetailsResponse.details:type_name -> catalog.GameDetails
	3,  // 10: catalog.GetSeriesDetailsResponse.details:type_name -> catalog.SeriesDetails
	6,  // 11: catalog.GetBookDetailsResponse.details:type_name -> catalog.BookDetails
	11, // 12: catalog.CatalogService.CreateContent:input_type -> catalog.CreateContentRequest
	7,  // 13: catalog.CatalogService.GetContent:input_type -> catalog.GetContentRequest
	13, // 14: catalog.CatalogService.UpdateContent:input_type -> catalog.UpdateContentRequest
	9,  // 15: catalog.CatalogService.FindContentByExternal:input_type -> catalog.FindContentByExternalRequest
	15, // 16: catalog.CatalogService.GetMovieDetails:input_type -> catalog.GetMovieDetailsRequest
	17, // 17: catalog.CatalogService.GetAnimeDetails:input_type -> catalog.GetAnimeDetailsRequest
	19, // 18: catalog.CatalogService.GetGameDetails:input_type -> catalog.GetGameDetailsRequest
	21, // 19: catalog.CatalogService.GetSeriesDetails:input_type -> catalog.GetSeriesDetailsRequest
	23, // 20: catalog.CatalogService.GetBookDetails:input_type -> catalog.GetBookDetailsRequest
	12, // 21: catalog.CatalogService.CreateContent:output_type -> catalog.CreateContentResponse
	8,  // 22: catalog.CatalogService.GetContent:output_type -> catalog.GetContentResponse
	14, // 23: catalog.CatalogService.UpdateContent:output_type -> catalog.UpdateContentResponse
	10, // 24: catalog.CatalogService.FindContentByExternal:output_type -> catalog.FindContentByExternalResponse
	16, // 25: catalog.CatalogService.GetMovieDetails:output_type -> catalog.GetMovieDetailsResponse
	18, // 26: catalog.CatalogService.GetAnimeDetails:output_type -> catalog.GetAnimeDetailsResponse
	20, // 27: catalog.CatalogService.GetGameDetails:output_type -> catalog.GetGameDetailsResponse
	22, // 28: catalog.CatalogService.GetSeriesDetails:output_type -> catalog.GetSeriesDetailsResponse
	24, // 29: catalog.CatalogService.GetBookDetails:output_type -> catalog.GetBookDetailsResponse
	21, // [21:30] is the sub-list for method output_type
	12, // [12:21] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_catalog_system_catalog_proto_init() }
func file_catalog_system_catalog_proto_init() {
	if File_catalog_system_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_system_catalog_proto_rawDesc), len(file_catalog_system_catalog_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_catalog_system_catalog_proto_goTypes,
		DependencyIndexes: file_catalog_system_catalog_proto_depIdxs,
		EnumInfos:         file_catalog_system_catalog_proto_enumTypes,
		MessageInfos:      file_catalog_system_catalog_proto_msgTypes,
	}.Build()
	File_catalog_system_catalog_proto = out.File
	file_catalog_system_catalog_proto_goTypes = nil
	file_catalog_system_catalog_proto_depIdxs = nil
}
