// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: catalog-system/catalog.proto

package catalogpb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Content with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Content) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Content with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in ContentMultiError, or nil if none found.
func (m *Content) ValidateAll() error {
	return m.validate(true)
}

func (m *Content) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Type

	// no validation rules for ExternalSource

	// no validation rules for ExternalId

	// no validation rules for Title

	// no validation rules for Description

	// no validation rules for PosterUrl

	// no validation rules for ReleaseDate

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	if len(errors) > 0 {
		return ContentMultiError(errors)
	}

	return nil
}

// ContentMultiError is an error wrapping multiple validation errors returned
// by Content.ValidateAll() if the designated constraints aren't met.
type ContentMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ContentMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ContentMultiError) AllErrors() []error { return m }

// ContentValidationError is the validation error returned by Content.Validate
// if the designated constraints aren't met.
type ContentValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ContentValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ContentValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ContentValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ContentValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ContentValidationError) ErrorName() string { return "ContentValidationError" }

// Error satisfies the builtin error interface
func (e ContentValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sContent.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ContentValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ContentValidationError{}

// Validate checks the field values on MovieDetails with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *MovieDetails) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MovieDetails with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in MovieDetailsMultiError, or
// nil if none found.
func (m *MovieDetails) ValidateAll() error {
	return m.validate(true)
}

func (m *MovieDetails) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ContentId

	// no validation rules for TmdbId

	// no validation rules for OriginalTitle

	// no validation rules for Runtime

	// no validation rules for Tagline

	// no validation rules for Status

	// no validation rules for Budget

	// no validation rules for Revenue

	// no validation rules for Language

	// no validation rules for GenresJson

	// no validation rules for CastJson

	// no validation rules for CrewJson

	// no validation rules for ImagesJson

	// no validation rules for VideosJson

	// no validation rules for RawJson

	if len(errors) > 0 {
		return MovieDetailsMultiError(errors)
	}

	return nil
}

// MovieDetailsMultiError is an error wrapping multiple validation errors
// returned by MovieDetails.ValidateAll() if the designated constraints aren't met.
type MovieDetailsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MovieDetailsMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MovieDetailsMultiError) AllErrors() []error { return m }

// MovieDetailsValidationError is the validation error returned by
// MovieDetails.Validate if the designated constraints aren't met.
type MovieDetailsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MovieDetailsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MovieDetailsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MovieDetailsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MovieDetailsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MovieDetailsValidationError) ErrorName() string { return "MovieDetailsValidationError" }

// Error satisfies the builtin error interface
func (e MovieDetailsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMovieDetails.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MovieDetailsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MovieDetailsValidationError{}

// Validate checks the field values on SeriesDetails with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SeriesDetails) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SeriesDetails with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SeriesDetailsMultiError, or
// nil if none found.
func (m *SeriesDetails) ValidateAll() error {
	return m.validate(true)
}

func (m *SeriesDetails) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ContentId

	// no validation rules for TmdbId

	// no validation rules for OriginalName

	// no validation rules for Status

	// no validation rules for FirstAirDate

	// no validation rules for LastAirDate

	// no validation rules for NumberOfSeasons

	// no validation rules for NumberOfEpisodes

	// no validation rules for Language

	// no validation rules for GenresJson

	// no validation rules for NetworksJson

	// no validation rules for CastJson

	// no validation rules for ImagesJson

	// no validation rules for VideosJson

	// no validation rules for RawJson

	if len(errors) > 0 {
		return SeriesDetailsMultiError(errors)
	}

	return nil
}

// SeriesDetailsMultiError is an error wrapping multiple validation errors
// returned by SeriesDetails.ValidateAll() if the designated constraints
// aren't met.
type SeriesDetailsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SeriesDetailsMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SeriesDetailsMultiError) AllErrors() []error { return m }

// SeriesDetailsValidationError is the validation error returned by
// SeriesDetails.Validate if the designated constraints aren't met.
type SeriesDetailsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SeriesDetailsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SeriesDetailsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SeriesDetailsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SeriesDetailsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SeriesDetailsValidationError) ErrorName() string { return "SeriesDetailsValidationError" }

// Error satisfies the builtin error interface
func (e SeriesDetailsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSeriesDetails.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SeriesDetailsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SeriesDetailsValidationError{}

// Validate checks the field values on AnimeDetails with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AnimeDetails) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AnimeDetails with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AnimeDetailsMultiError, or
// nil if none found.
func (m *AnimeDetails) ValidateAll() error {
	return m.validate(true)
}

func (m *AnimeDetails) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ContentId

	// no validation rules for AnilistId

	// no validation rules for MalId

	// no validation rules for OriginalTitle

	// no validation rules for Format

	// no validation rules for Status

	// no validation rules for Season

	// no validation rules for SeasonYear

	// no validation rules for EpisodesCount

	// no validation rules for EpisodeDuration

	// no validation rules for StartDate

	// no validation rules for EndDate

	// no validation rules for Language

	// no validation rules for GenresJson

	// no validation rules for TagsJson

	// no validation rules for StudiosJson

	// no validation rules for CharactersJson

	// no validation rules for VoiceActorsJson

	// no validation rules for MeanScore

	// no validation rules for Popularity

	// no validation rules for Favourites

	// no validation rules for TrailerUrl

	// no validation rules for RawJson

	if len(errors) > 0 {
		return AnimeDetailsMultiError(errors)
	}

	return nil
}

// AnimeDetailsMultiError is an error wrapping multiple validation errors
// returned by AnimeDetails.ValidateAll() if the designated constraints aren't met.
type AnimeDetailsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AnimeDetailsMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AnimeDetailsMultiError) AllErrors() []error { return m }

// AnimeDetailsValidationError is the validation error returned by
// AnimeDetails.Validate if the designated constraints aren't met.
type AnimeDetailsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AnimeDetailsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AnimeDetailsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AnimeDetailsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AnimeDetailsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AnimeDetailsValidationError) ErrorName() string { return "AnimeDetailsValidationError" }

// Error satisfies the builtin error interface
func (e AnimeDetailsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAnimeDetails.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AnimeDetailsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AnimeDetailsValidationError{}

// Validate checks the field values on GameDetails with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GameDetails) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GameDetails with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GameDetailsMultiError, or
// nil if none found.
func (m *GameDetails) ValidateAll() error {
	return m.validate(true)
}

func (m *GameDetails) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ContentId

	// no validation rules for IgdbId

	// no validation rules for Rating

	// no validation rules for GenresJson

	// no validation rules for PlatformsJson

	// no validation rules for DevelopersJson

	// no validation rules for PublishersJson

	// no validation rules for ScreenshotsJson

	// no validation rules for RawJson

	if len(errors) > 0 {
		return GameDetailsMultiError(errors)
	}

	return nil
}

// GameDetailsMultiError is an error wrapping multiple validation errors
// returned by GameDetails.ValidateAll() if the designated constraints aren't met.
type GameDetailsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GameDetailsMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GameDetailsMultiError) AllErrors() []error { return m }

// GameDetailsValidationError is the validation error returned by
// GameDetails.Validate if the designated constraints aren't met.
type GameDetailsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GameDetailsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GameDetailsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GameDetailsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GameDetailsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GameDetailsValidationError) ErrorName() string { return "GameDetailsValidationError" }

// Error satisfies the builtin error interface
func (e GameDetailsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGameDetails.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GameDetailsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GameDetailsValidationError{}

// Validate checks the field values on BookDetails with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *BookDetails) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BookDetails with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in BookDetailsMultiError, or
// nil if none found.
func (m *BookDetails) ValidateAll() error {
	return m.validate(true)
}

func (m *BookDetails) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ContentId

	// no validation rules for Isbn_10

	// no validation rules for Isbn_13

	// no validation rules for Language

	// no validation rules for Pages

	// no validation rules for PublishDate

	// no validation rules for AuthorsJson

	// no validation rules for PublishersJson

	// no validation rules for GenresJson

	// no validation rules for RawJson

	if len(errors) > 0 {
		return BookDetailsMultiError(errors)
	}

	return nil
}

// BookDetailsMultiError is an error wrapping multiple validation errors
// returned by BookDetails.ValidateAll() if the designated constraints aren't met.
type BookDetailsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BookDetailsMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BookDetailsMultiError) AllErrors() []error { return m }

// BookDetailsValidationError is the validation error returned by
// BookDetails.Validate if the designated constraints aren't met.
type BookDetailsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BookDetailsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BookDetailsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BookDetailsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BookDetailsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BookDetailsValidationError) ErrorName() string { return "BookDetailsValidationError" }

// Error satisfies the builtin error interface
func (e BookDetailsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBookDetails.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BookDetailsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BookDetailsValidationError{}

// Validate checks the field values on GetContentRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetContentRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetContentRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetContentRequestMultiError, or nil if none found.
func (m *GetContentRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetContentRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return GetContentRequestMultiError(errors)
	}

	return nil
}

// GetContentRequestMultiError is an error wrapping multiple validation errors
// returned by GetContentRequest.ValidateAll() if the designated constraints
// aren't met.
type GetContentRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetContentRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetContentRequestMultiError) AllErrors() []error { return m }

// GetContentRequestValidationError is the validation error returned by
// GetContentRequest.Validate if the designated constraints aren't met.
type GetContentRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetContentRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetContentRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetContentRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetContentRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetContentRequestValidationError) ErrorName() string {
	return "GetContentRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetContentRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetContentRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetContentRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetContentRequestValidationError{}

// Validate checks the field values on GetContentResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetContentResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetContentResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetContentResponseMultiError, or nil if none found.
func (m *GetContentResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetContentResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetContent()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetContentResponseValidationError{
					field:  "Content",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetContentResponseValidationError{
					field:  "Content",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetContent()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetContentResponseValidationError{
				field:  "Content",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetContentResponseMultiError(errors)
	}

	return nil
}

// GetContentResponseMultiError is an error wrapping multiple validation errors
// returned by GetContentResponse.ValidateAll() if the designated constraints
// aren't met.
type GetContentResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetContentResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetContentResponseMultiError) AllErrors() []error { return m }

// GetContentResponseValidationError is the validation error returned by
// GetContentResponse.Validate if the designated constraints aren't met.
type GetContentResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetContentResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetContentResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetContentResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetContentResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetContentResponseValidationError) ErrorName() string {
	return "GetContentResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetContentResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetContentResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetContentResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetContentResponseValidationError{}

// Validate checks the field values on FindContentByExternalRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *FindContentByExternalRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FindContentByExternalRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// FindContentByExternalRequestMultiError, or nil if none found.
func (m *FindContentByExternalRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *FindContentByExternalRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ExternalSource

	// no validation rules for ExternalId

	if len(errors) > 0 {
		return FindContentByExternalRequestMultiError(errors)
	}

	return nil
}

// FindContentByExternalRequestMultiError is an error wrapping multiple
// validation errors returned by FindContentByExternalRequest.ValidateAll() if
// the designated constraints aren't met.
type FindContentByExternalRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FindContentByExternalRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FindContentByExternalRequestMultiError) AllErrors() []error { return m }

// FindContentByExternalRequestValidationError is the validation error returned
// by FindContentByExternalRequest.Validate if the designated constraints
// aren't met.
type FindContentByExternalRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FindContentByExternalRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FindContentByExternalRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FindContentByExternalRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FindContentByExternalRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FindContentByExternalRequestValidationError) ErrorName() string {
	return "FindContentByExternalRequestValidationError"
}

// Error satisfies the builtin error interface
func (e FindContentByExternalRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFindContentByExternalRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FindContentByExternalRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FindContentByExternalRequestValidationError{}

// Validate checks the field values on FindContentByExternalResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *FindContentByExternalResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FindContentByExternalResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// FindContentByExternalResponseMultiError, or nil if none found.
func (m *FindContentByExternalResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *FindContentByExternalResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetContent()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, FindContentByExternalResponseValidationError{
					field:  "Content",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, FindContentByExternalResponseValidationError{
					field:  "Content",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetContent()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return FindContentByExternalResponseValidationError{
				field:  "Content",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return FindContentByExternalResponseMultiError(errors)
	}

	return nil
}

// FindContentByExternalResponseMultiError is an error wrapping multiple
// validation errors returned by FindContentByExternalResponse.ValidateAll()
// if the designated constraints aren't met.
type FindContentByExternalResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FindContentByExternalResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FindContentByExternalResponseMultiError) AllErrors() []error { return m }

// FindContentByExternalResponseValidationError is the validation error
// returned by FindContentByExternalResponse.Validate if the designated
// constraints aren't met.
type FindContentByExternalResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FindContentByExternalResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FindContentByExternalResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FindContentByExternalResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FindContentByExternalResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FindContentByExternalResponseValidationError) ErrorName() string {
	return "FindContentByExternalResponseValidationError"
}

// Error satisfies the builtin error interface
func (e FindContentByExternalResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFindContentByExternalResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FindContentByExternalResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FindContentByExternalResponseValidationError{}

// Validate checks the field values on CreateContentRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateContentRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateContentRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateContentRequestMultiError, or nil if none found.
func (m *CreateContentRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateContentRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetContent()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateContentRequestValidationError{
					field:  "Content",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateContentRequestValidationError{
					field:  "Content",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetContent()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateContentRequestValidationError{
				field:  "Content",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateContentRequestMultiError(errors)
	}

	return nil
}

// CreateContentRequestMultiError is an error wrapping multiple validation
// errors returned by CreateContentRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateContentRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateContentRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateContentRequestMultiError) AllErrors() []error { return m }

// CreateContentRequestValidationError is the validation error returned by
// CreateContentRequest.Validate if the designated constraints aren't met.
type CreateContentRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateContentRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateContentRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateContentRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateContentRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateContentRequestValidationError) ErrorName() string {
	return "CreateContentRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateContentRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateContentRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateContentRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateContentRequestValidationError{}

// Validate checks the field values on CreateContentResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateContentResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateContentResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateContentResponseMultiError, or nil if none found.
func (m *CreateContentResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateContentResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetContent()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateContentResponseValidationError{
					field:  "Content",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateContentResponseValidationError{
					field:  "Content",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetContent()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateContentResponseValidationError{
				field:  "Content",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateContentResponseMultiError(errors)
	}

	return nil
}

// CreateContentResponseMultiError is an error wrapping multiple validation
// errors returned by CreateContentResponse.ValidateAll() if the designated
// constraints aren't met.
type CreateContentResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateContentResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateContentResponseMultiError) AllErrors() []error { return m }

// CreateContentResponseValidationError is the validation error returned by
// CreateContentResponse.Validate if the designated constraints aren't met.
type CreateContentResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateContentResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateContentResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateContentResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateContentResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateContentResponseValidationError) ErrorName() string {
	return "CreateContentResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateContentResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateContentResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateContentResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateContentResponseValidationError{}

// Validate checks the field values on UpdateContentRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateContentRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateContentRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateContentRequestMultiError, or nil if none found.
func (m *UpdateContentRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateContentRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetContent()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateContentRequestValidationError{
					field:  "Content",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateContentRequestValidationError{
					field:  "Content",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetContent()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateContentRequestValidationError{
				field:  "Content",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UpdateContentRequestMultiError(errors)
	}

	return nil
}

// UpdateContentRequestMultiError is an error wrapping multiple validation
// errors returned by UpdateContentRequest.ValidateAll() if the designated
// constraints aren't met.
type UpdateContentRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateContentRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateContentRequestMultiError) AllErrors() []error { return m }

// UpdateContentRequestValidationError is the validation error returned by
// UpdateContentRequest.Validate if the designated constraints aren't met.
type UpdateContentRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateContentRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateContentRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateContentRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateContentRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateContentRequestValidationError) ErrorName() string {
	return "UpdateContentRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateContentRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateContentRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateContentRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateContentRequestValidationError{}

// Validate checks the field values on UpdateContentResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateContentResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateContentResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateContentResponseMultiError, or nil if none found.
func (m *UpdateContentResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateContentResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetContent()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateContentResponseValidationError{
					field:  "Content",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateContentResponseValidationError{
					field:  "Content",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetContent()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateContentResponseValidationError{
				field:  "Content",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UpdateContentResponseMultiError(errors)
	}

	return nil
}

// UpdateContentResponseMultiError is an error wrapping multiple validation
// errors returned by UpdateContentResponse.ValidateAll() if the designated
// constraints aren't met.
type UpdateContentResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateContentResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateContentResponseMultiError) AllErrors() []error { return m }

// UpdateContentResponseValidationError is the validation error returned by
// UpdateContentResponse.Validate if the designated constraints aren't met.
type UpdateContentResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateContentResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateContentResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateContentResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateContentResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateContentResponseValidationError) ErrorName() string {
	return "UpdateContentResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateContentResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateContentResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateContentResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateContentResponseValidationError{}

// Validate checks the field values on GetMovieDetailsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetMovieDetailsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetMovieDetailsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetMovieDetailsRequestMultiError, or nil if none found.
func (m *GetMovieDetailsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetMovieDetailsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ContentId

	if len(errors) > 0 {
		return GetMovieDetailsRequestMultiError(errors)
	}

	return nil
}

// GetMovieDetailsRequestMultiError is an error wrapping multiple validation
// errors returned by GetMovieDetailsRequest.ValidateAll() if the designated
// constraints aren't met.
type GetMovieDetailsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetMovieDetailsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetMovieDetailsRequestMultiError) AllErrors() []error { return m }

// GetMovieDetailsRequestValidationError is the validation error returned by
// GetMovieDetailsRequest.Validate if the designated constraints aren't met.
type GetMovieDetailsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetMovieDetailsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetMovieDetailsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetMovieDetailsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetMovieDetailsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetMovieDetailsRequestValidationError) ErrorName() string {
	return "GetMovieDetailsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetMovieDetailsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetMovieDetailsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetMovieDetailsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetMovieDetailsRequestValidationError{}

// Validate checks the field values on GetMovieDetailsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetMovieDetailsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetMovieDetailsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetMovieDetailsResponseMultiError, or nil if none found.
func (m *GetMovieDetailsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetMovieDetailsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetDetails()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetMovieDetailsResponseValidationError{
					field:  "Details",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetMovieDetailsResponseValidationError{
					field:  "Details",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDetails()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetMovieDetailsResponseValidationError{
				field:  "Details",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetMovieDetailsResponseMultiError(errors)
	}

	return nil
}

// GetMovieDetailsResponseMultiError is an error wrapping multiple validation
// errors returned by GetMovieDetailsResponse.ValidateAll() if the designated
// constraints aren't met.
type GetMovieDetailsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetMovieDetailsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetMovieDetailsResponseMultiError) AllErrors() []error { return m }

// GetMovieDetailsResponseValidationError is the validation error returned by
// GetMovieDetailsResponse.Validate if the designated constraints aren't met.
type GetMovieDetailsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetMovieDetailsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetMovieDetailsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetMovieDetailsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetMovieDetailsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetMovieDetailsResponseValidationError) ErrorName() string {
	return "GetMovieDetailsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetMovieDetailsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetMovieDetailsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetMovieDetailsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetMovieDetailsResponseValidationError{}

// Validate checks the field values on GetAnimeDetailsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetAnimeDetailsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetAnimeDetailsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetAnimeDetailsRequestMultiError, or nil if none found.
func (m *GetAnimeDetailsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetAnimeDetailsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ContentId

	if len(errors) > 0 {
		return GetAnimeDetailsRequestMultiError(errors)
	}

	return nil
}

// GetAnimeDetailsRequestMultiError is an error wrapping multiple validation
// errors returned by GetAnimeDetailsRequest.ValidateAll() if the designated
// constraints aren't met.
type GetAnimeDetailsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetAnimeDetailsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetAnimeDetailsRequestMultiError) AllErrors() []error { return m }

// GetAnimeDetailsRequestValidationError is the validation error returned by
// GetAnimeDetailsRequest.Validate if the designated constraints aren't met.
type GetAnimeDetailsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetAnimeDetailsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetAnimeDetailsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetAnimeDetailsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetAnimeDetailsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetAnimeDetailsRequestValidationError) ErrorName() string {
	return "GetAnimeDetailsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetAnimeDetailsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetAnimeDetailsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetAnimeDetailsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetAnimeDetailsRequestValidationError{}

// Validate checks the field values on GetAnimeDetailsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetAnimeDetailsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetAnimeDetailsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetAnimeDetailsResponseMultiError, or nil if none found.
func (m *GetAnimeDetailsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetAnimeDetailsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetDetails()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetAnimeDetailsResponseValidationError{
					field:  "Details",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetAnimeDetailsResponseValidationError{
					field:  "Details",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDetails()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetAnimeDetailsResponseValidationError{
				field:  "Details",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetAnimeDetailsResponseMultiError(errors)
	}

	return nil
}

// GetAnimeDetailsResponseMultiError is an error wrapping multiple validation
// errors returned by GetAnimeDetailsResponse.ValidateAll() if the designated
// constraints aren't met.
type GetAnimeDetailsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetAnimeDetailsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetAnimeDetailsResponseMultiError) AllErrors() []error { return m }

// GetAnimeDetailsResponseValidationError is the validation error returned by
// GetAnimeDetailsResponse.Validate if the designated constraints aren't met.
type GetAnimeDetailsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetAnimeDetailsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetAnimeDetailsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetAnimeDetailsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetAnimeDetailsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetAnimeDetailsResponseValidationError) ErrorName() string {
	return "GetAnimeDetailsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetAnimeDetailsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetAnimeDetailsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetAnimeDetailsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetAnimeDetailsResponseValidationError{}

// Validate checks the field values on GetGameDetailsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetGameDetailsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetGameDetailsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetGameDetailsRequestMultiError, or nil if none found.
func (m *GetGameDetailsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetGameDetailsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ContentId

	if len(errors) > 0 {
		return GetGameDetailsRequestMultiError(errors)
	}

	return nil
}

// GetGameDetailsRequestMultiError is an error wrapping multiple validation
// errors returned by GetGameDetailsRequest.ValidateAll() if the designated
// constraints aren't met.
type GetGameDetailsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetGameDetailsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetGameDetailsRequestMultiError) AllErrors() []error { return m }

// GetGameDetailsRequestValidationError is the validation error returned by
// GetGameDetailsRequest.Validate if the designated constraints aren't met.
type GetGameDetailsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetGameDetailsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetGameDetailsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetGameDetailsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetGameDetailsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetGameDetailsRequestValidationError) ErrorName() string {
	return "GetGameDetailsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetGameDetailsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetGameDetailsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetGameDetailsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetGameDetailsRequestValidationError{}

// Validate checks the field values on GetGameDetailsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetGameDetailsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetGameDetailsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetGameDetailsResponseMultiError, or nil if none found.
func (m *GetGameDetailsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetGameDetailsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetDetails()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetGameDetailsResponseValidationError{
					field:  "Details",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetGameDetailsResponseValidationError{
					field:  "Details",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDetails()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetGameDetailsResponseValidationError{
				field:  "Details",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetGameDetailsResponseMultiError(errors)
	}

	return nil
}

// GetGameDetailsResponseMultiError is an error wrapping multiple validation
// errors returned by GetGameDetailsResponse.ValidateAll() if the designated
// constraints aren't met.
type GetGameDetailsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetGameDetailsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetGameDetailsResponseMultiError) AllErrors() []error { return m }

// GetGameDetailsResponseValidationError is the validation error returned by
// GetGameDetailsResponse.Validate if the designated constraints aren't met.
type GetGameDetailsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetGameDetailsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetGameDetailsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetGameDetailsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetGameDetailsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetGameDetailsResponseValidationError) ErrorName() string {
	return "GetGameDetailsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetGameDetailsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetGameDetailsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetGameDetailsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetGameDetailsResponseValidationError{}

// Validate checks the field values on GetSeriesDetailsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetSeriesDetailsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetSeriesDetailsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetSeriesDetailsRequestMultiError, or nil if none found.
func (m *GetSeriesDetailsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetSeriesDetailsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ContentId

	if len(errors) > 0 {
		return GetSeriesDetailsRequestMultiError(errors)
	}

	return nil
}

// GetSeriesDetailsRequestMultiError is an error wrapping multiple validation
// errors returned by GetSeriesDetailsRequest.ValidateAll() if the designated
// constraints aren't met.
type GetSeriesDetailsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetSeriesDetailsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetSeriesDetailsRequestMultiError) AllErrors() []error { return m }

// GetSeriesDetailsRequestValidationError is the validation error returned by
// GetSeriesDetailsRequest.Validate if the designated constraints aren't met.
type GetSeriesDetailsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetSeriesDetailsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetSeriesDetailsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetSeriesDetailsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetSeriesDetailsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetSeriesDetailsRequestValidationError) ErrorName() string {
	return "GetSeriesDetailsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetSeriesDetailsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetSeriesDetailsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetSeriesDetailsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetSeriesDetailsRequestValidationError{}

// Validate checks the field values on GetSeriesDetailsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetSeriesDetailsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetSeriesDetailsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetSeriesDetailsResponseMultiError, or nil if none found.
func (m *GetSeriesDetailsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetSeriesDetailsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetDetails()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetSeriesDetailsResponseValidationError{
					field:  "Details",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetSeriesDetailsResponseValidationError{
					field:  "Details",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDetails()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetSeriesDetailsResponseValidationError{
				field:  "Details",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetSeriesDetailsResponseMultiError(errors)
	}

	return nil
}

// GetSeriesDetailsResponseMultiError is an error wrapping multiple validation
// errors returned by GetSeriesDetailsResponse.ValidateAll() if the designated
// constraints aren't met.
type GetSeriesDetailsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetSeriesDetailsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetSeriesDetailsResponseMultiError) AllErrors() []error { return m }

// GetSeriesDetailsResponseValidationError is the validation error returned by
// GetSeriesDetailsResponse.Validate if the designated constraints aren't met.
type GetSeriesDetailsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetSeriesDetailsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetSeriesDetailsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetSeriesDetailsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetSeriesDetailsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetSeriesDetailsResponseValidationError) ErrorName() string {
	return "GetSeriesDetailsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetSeriesDetailsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetSeriesDetailsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetSeriesDetailsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetSeriesDetailsResponseValidationError{}

// Validate checks the field values on GetBookDetailsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetBookDetailsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetBookDetailsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetBookDetailsRequestMultiError, or nil if none found.
func (m *GetBookDetailsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetBookDetailsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ContentId

	if len(errors) > 0 {
		return GetBookDetailsRequestMultiError(errors)
	}

	return nil
}

// GetBookDetailsRequestMultiError is an error wrapping multiple validation
// errors returned by GetBookDetailsRequest.ValidateAll() if the designated
// constraints aren't met.
type GetBookDetailsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetBookDetailsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetBookDetailsRequestMultiError) AllErrors() []error { return m }

// GetBookDetailsRequestValidationError is the validation error returned by
// GetBookDetailsRequest.Validate if the designated constraints aren't met.
type GetBookDetailsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetBookDetailsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetBookDetailsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetBookDetailsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetBookDetailsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetBookDetailsRequestValidationError) ErrorName() string {
	return "GetBookDetailsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetBookDetailsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetBookDetailsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetBookDetailsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetBookDetailsRequestValidationError{}

// Validate checks the field values on GetBookDetailsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetBookDetailsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetBookDetailsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetBookDetailsResponseMultiError, or nil if none found.
func (m *GetBookDetailsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetBookDetailsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetDetails()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetBookDetailsResponseValidationError{
					field:  "Details",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetBookDetailsResponseValidationError{
					field:  "Details",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDetails()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetBookDetailsResponseValidationError{
				field:  "Details",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetBookDetailsResponseMultiError(errors)
	}

	return nil
}

// GetBookDetailsResponseMultiError is an error wrapping multiple validation
// errors returned by GetBookDetailsResponse.ValidateAll() if the designated
// constraints aren't met.
type GetBookDetailsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetBookDetailsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetBookDetailsResponseMultiError) AllErrors() []error { return m }

// GetBookDetailsResponseValidationError is the validation error returned by
// GetBookDetailsResponse.Validate if the designated constraints aren't met.
type GetBookDetailsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetBookDetailsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetBookDetailsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetBookDetailsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetBookDetailsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetBookDetailsResponseValidationError) ErrorName() string {
	return "GetBookDetailsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetBookDetailsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetBookDetailsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetBookDetailsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetBookDetailsResponseValidationError{}
