# catalog-system-microservice/Dockerfile.importer
FROM golang:1.25.3-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -o /app/bin/importer ./cmd/importer/main.go

FROM alpine:3.19

RUN apk --no-cache add ca-certificates bash

WORKDIR /app

COPY --from=builder /app/bin/importer /app/importer
COPY --from=builder /app/config /app/config

# имортер завершается сам после работы
CMD ["/app/importer", "--config=/app/config/local.yaml"]